INCLUDE FILE(fiends/include/animate_dead.ssl)

INCLUDE FILE(fiends/include/nycaloth/mirror_image.ssl)

INCLUDE FILE(fiends/include/nycaloth/fear.ssl)

INCLUDE FILE(fiends/include/nycaloth/cause_disease.ssl)

BEGIN LOOP(fl#spellprobability||50)
  INCLUDE FILE(fiends/include/charm_person.ssl)
END LOOP

INCLUDE FILE(fiends/include/nycaloth/produce_flame.ssl)

INCLUDE FILE(fiends/include/nycaloth/command.ssl)

INCLUDE FILE(fiends/include/produce_flame.ssl)
