IF
  TargetBlock(EnemiesInOrder)
  TriggerBlock(Disabled|Enemy)
  Gender(scstarget,SUMMONED_DEMON)
  !ChechStatGT(Myself,0,PROTECTION_FROM_EVIL)
THEN DO
  Action(SpellMyself,CLERIC_PROTECTION_FROM_EVIL_10_FOOT|200|50)
END

IF TRIGGER
  TargetBlock(EnemiesInOrder)
  TriggerBlock(Disabled|Enemy)
  Gender(scstarget,SUMMONED_DEMON)
  !ChechStatGT(Myself,0,PROTECTION_FROM_EVIL)
THEN DO
  Action(SpellMyself,CLERIC_PROTECTION_FROM_EVIL|200|50)
END
