IF
  Global("RR#NOPND","GLOBAL",0) // opening doors is allowed
  Allegiance(Myself,EVILCUTOFF) // humanoids and some intelligent monsters can open unlocked doors
  !AreaType(OUTDOOR)
  !Range(NearestEnemyOf(Myself),30)
  Range(NearestDoor,15) // if the nearest door is in visual range. note: this seems to auto-skip locked doors
  OpenState(NearestDoor,FALSE)
THEN
  RESPONSE #100
    MoveToObject(NearestDoor)
    OpenDoor(NearestDoor)
END
