IF TRIGGER
  TargetBlock(EnemiesInOrder)
  TriggerBlock(CanCastMage|SpellTurning|SIAbj|Disabled)
  OR(5)
    CheckStatGT(scstarget,0,TRUE_SIGHT)
    CheckStatGT(scstarget,0,STONESKINS)
    CheckStatGT(scstarget,0,CLERIC_CHAOTIC_COMMANDS)
    CheckStatGT(scstarget,0,CLERIC_FREE_ACTION)
    CheckStatGT(scstarget,0,WIZARD_RESIST_FEAR)
  !Race(scstarget,RAKSHASA)
  !Race(scstarget,LICH)
THEN DO
  Combine()
  Action(Spell,WIZARD_BREACH|100|33)
END
