INCLUDE FILE(include/definitions.ssl)

BEGIN LOOP (EnemyReplacementScript||fl#lowm)
  INCLUDE FILE(include/summoned_top.ssl)
END LOOP

IF
  StateCheck(Myself,STATE_CHARMED)
  See(NearestEnemyOf(Myself))
  ActionListEmpty()
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    Attack(LastSeenBy(Myself))
END

DEFAULT TRIGGER(ActionListEmpty())

INCLUDE FILE(general/melee_mindless.ssl)

DEFAULT TRIGGER()
