IF
  Die()
THEN
  RESPONSE #100
    %TutuJournal%
END

IF
  Dead("gooddeat")
THEN
  RESPONSE #100
    ChangeAIScript("fl#bg1kn",OVERRIDE)
END

//Fear aura every round
IF
  !StateCheck(Myself,STATE_REALLY_DEAD)
  !GlobalTimerNotExpired("flFearAura","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("flFearAura","LOCALS",6)
    ApplySpellRES("FLDKAURA",Myself)
    Continue()
END

IF
  See("gooddeat")
THEN
  RESPONSE #100
    AttackOneRound("gooddeat")
END
