IF TRIGGER
  TargetBlock(EnemiesInOrder)
  TriggerBlock(Enemy|Disabled|MR|MagicDamage50|SINec)
  !Gender(scstarget,SUMMONED)
  !HasItemEquiped("clck26",scstarget)
THEN DO
    Action(Spell,WIZARD_ABI_DALZIMS_HORRID_WILTING|100|100)
END

//Maybe something for taking out Mordy Swords

IF TRIGGER
  StateCheck(Myself,STATE_BLIND)
  TriggerBlock(PlayersInRangeShort)
THEN DO
    Action(SpellMyself,WIZARD_ABI_DALZIMS_HORRID_WILTING|150|100)
END
