IF
	!StateCheck(Myself,STATE_CHARMED)
	See([0.0.DEMONIC.0.0.SUMMONED_DEMON])
	Gender(Myself,MALE)
	General(Myself,HUMANOID)
THEN
	RESPONSE #100
		PlaySound("PEASM209")
		RandomWalkContinuous()
END

IF
        !StateCheck(Myself,STATE_CHARMED)
	See([0.0.DEMONIC.0.0.SUMMONED_DEMON])
	Gender(Myself,FEMALE)
	General(Myself,HUMANOID)
THEN
	RESPONSE #100
		PlaySound("PEASF209")
		RandomWalkContinuous()
END