IF TRIGGER
  TargetBlock(EnemiesInOrder)
  TriggerBlock(Disabled|Enemy)
  !See([ENEMY.UNDEAD.0.0.0.SUMMONED])
  !See([ENEMY.UNDEAD.0.0.0.20])
THEN DO
  Combine()
  Action(Spell,CLERIC_ANIMATE_DEAD|100|50)
END

IF TRIGGER
  TargetBlock(EnemiesInOrder)
  TriggerBlock(Disabled|Enemy)
  !See([ENEMY.0.0.ELEMENTAL_AIR.0.SUMMONED])
  !See([ENEMY.0.0.ELEMENTAL_AIR.0.20])
THEN DO
  Combine()
  Action(Spell,CLERIC_AERIAL_SERVANT|100|200)
END
