///////////////
// PnP Mephits
///////////////

INCLUDE "atweaks/lib/dsandstuff.tpa"                                               // Detectable Spells



//////////////
// New spells
//////////////


COPY ~atweaks/spl/mephits/rr#maigt.spl~ ~override~                                 // Gate (Air Mephit)
COPY ~atweaks/eff/mephits/rr#maigt.eff~ ~override~                                 // Gate EFF (Air Mephit)
COPY ~atweaks/spl/mephits/rr#maibg.spl~ ~override~                                 // Breathe Grit (Air Mephit)
COPY ~atweaks/spl/mephits/rr#maigw.spl~ ~override~                                 // Gust of Wind (Air Mephit)
  SAY NAME1 @1850 SAY NAME2 @1850

COPY ~atweaks/spl/mephits/rr#mdugt.spl~ ~override~                                 // Gate (Dust Mephit)
COPY ~atweaks/eff/mephits/rr#mdugt.eff~ ~override~                                 // Gate EFF (Dust Mephit)
COPY ~atweaks/spl/mephits/rr#mdugd.spl~ ~override~                                 // Glass Dust, part 1 (Dust Mephit)
COPY ~atweaks/spl/mephits/rr#mdug2.spl~ ~override~                                 // Glass Dust, part 2 (Dust Mephit)
COPY ~atweaks/eff/mephits/rr#mdugd.eff~ ~override~                                 // Glass Dust EFF (Dust Mephit)

COPY ~atweaks/spl/mephits/rr#meagt.spl~ ~override~                                 // Gate (Earth Mephit)
COPY ~atweaks/eff/mephits/rr#meagt.eff~ ~override~                                 // Gate EFF (Earth Mephit)
COPY ~atweaks/spl/mephits/rr#meass.spl~ ~override~                                 // Stone Spit (Earth Mephit)
COPY ~atweaks/spl/mephits/rr#meagr.spl~ ~override~                                 // Grow (Earth Mephit)
  SAY NAME1 @1851 SAY NAME2 @1851

COPY ~atweaks/spl/mephits/rr#mfigt.spl~ ~override~                                 // Gate (Fire Mephit)
COPY ~atweaks/eff/mephits/rr#mfigt.eff~ ~override~                                 // Gate EFF (Fire Mephit)
ADD_PROJECTILE ~atweaks/pro/rr#mfiff.pro~                                          // New projectile for Flame Fan (120' arc, Burning Hands style)

COPY ~atweaks/spl/mephits/rr#mfiff.spl~ ~override~                                 // Flame Fan (Fire Mephit)
  READ_LONG  0x64 ab_off
  READ_SHORT 0x68 ab_num
  FOR(i=0; i<ab_num; i+=1) BEGIN
    WRITE_SHORT (ab_off+i*0x28+0x26) %rr#mfiff%                                    // use new projectile
  END 
COPY ~atweaks/spl/mephits/rr#mfifj.spl~ ~override~                                 // Flame Jet (Fire Mephit)
COPY ~atweaks/spl/mephits/rr#mfiha.spl~ ~override~                                 // Heat Aura (Fire Mephit)
  SAY NAME1 @1852 SAY NAME2 @1852

COPY ~atweaks/spl/mephits/rr#micgt.spl~ ~override~                                 // Gate (Ice Mephit)
COPY ~atweaks/eff/mephits/rr#micgt.eff~ ~override~                                 // Gate EFF (Ice Mephit)
COPY ~atweaks/spl/mephits/rr#micis.spl~ ~override~                                 // Ice Shard (Ice Mephit)


COPY ~atweaks/spl/mephits/rr#mligt.spl~ ~override~                                 // Gate (Lightning Mephit)
COPY ~atweaks/eff/mephits/rr#mligt.eff~ ~override~                                 // Gate EFF (Lightning Mephit)
COPY ~atweaks/bam/rr#mlilb.bam~ ~override~                                         // new Lightning Bolt animation (Icewind Dale style)
ADD_PROJECTILE ~atweaks/pro/rr#mlilb.pro~                                          // New projectile for Lightning Bolt (no bounce, high speed)
COPY ~atweaks/spl/mephits/rr#mlilb.spl~ ~override~                                 // Lightning Bolt (Lightning Mephit)
  READ_LONG  0x64 ab_off
  READ_SHORT 0x68 ab_num
  FOR(i=0; i<ab_num; i+=1) BEGIN
    WRITE_SHORT (ab_off+i*0x28+0x26) %rr#mlilb%                                    // use new projectile
  END 
COPY ~atweaks/spl/mephits/rr#mlild.spl~ ~override~                                 // Lightning Discharge (Lightning Mephit)
  SAY NAME1 @1854 SAY NAME2 @1854

COPY ~atweaks/spl/mephits/rr#mmagt.spl~ ~override~                                 // Gate (Magma Mephit)
COPY ~atweaks/eff/mephits/rr#mmagt.eff~ ~override~                                 // Gate EFF (Magma Mephit)
COPY ~atweaks/spl/mephits/rr#mmamb.spl~ ~override~                                 // Magma Ball (Magma Mephit)
COPY ~atweaks/spl/mephits/rr#mmahe.spl~ ~override~                                 // Heat Emission (Magma Mephit)
  SAY NAME1 @1853 SAY NAME2 @1853

COPY ~atweaks/spl/mephits/rr#mmigt.spl~ ~override~                                 // Gate (Mineral Mephit)
COPY ~atweaks/eff/mephits/rr#mmigt.eff~ ~override~                                 // Gate EFF (Mineral Mephit)


COPY ~atweaks/spl/mephits/rr#mmsgt.spl~ ~override~                                 // Gate (Mist Mephit)
COPY ~atweaks/eff/mephits/rr#mmsgt.eff~ ~override~                                 // Gate EFF (Mist Mephit)
COPY ~atweaks/spl/mephits/rr#mmsmb.spl~ ~override~                                 // Mist Ball (Mist Mephit)
COPY ~atweaks/spl/mephits/rr#mmsgf.spl~ ~override~                                 // Gaseous Form (Mist Mephit)
COPY ~atweaks/vvc/rr#mmswf.vvc~ ~override~                                         // Wall of Fog animation (Mist Mephit)
COPY ~atweaks/spl/mephits/rr#mmswf.spl~ ~override~                                 // Wall of Fog (Mist Mephit)
  SAY NAME1 @1855 SAY NAME2 @1855

COPY ~atweaks/spl/mephits/rr#mozgt.spl~ ~override~                                 // Gate (Ooze Mephit)
COPY ~atweaks/eff/mephits/rr#mozgt.eff~ ~override~                                 // Gate EFF (Ooze Mephit)


COPY ~atweaks/spl/mephits/rr#mragt.spl~ ~override~                                 // Gate (Radiant Mephit)
COPY ~atweaks/eff/mephits/rr#mragt.eff~ ~override~                                 // Gate EFF (Radiant Mephit)
COPY ~atweaks/spl/mephits/rr#mracs.spl~ ~override~                                 // Color Spray (special Radiant Mephit version)
COPY ~aTweaks/spl/rr#ddeti.spl~ ~override~                                         // Detect Illusion (Radiant Mephit & aTweaks' Marilith)

COPY ~atweaks/spl/mephits/rr#msagt.spl~ ~override~                                 // Gate (Salt Mephit)
COPY ~atweaks/eff/mephits/rr#msagt.eff~ ~override~                                 // Gate EFF (Salt Mephit)
COPY ~atweaks/spl/mephits/rr#msasc.spl~ ~override~                                 // Salt Crystals (Salt Mephit)
COPY ~atweaks/spl/mephits/rr#msata.spl~ ~override~                                 // Taunt (Salt Mephit)
  SAY NAME1 @1856 SAY NAME2 @1856

COPY ~atweaks/spl/mephits/rr#msmgt.spl~ ~override~                                 // Gate (Smoke Mephit)
COPY ~atweaks/eff/mephits/rr#msmgt.eff~ ~override~                                 // Gate EFF (Smoke Mephit)
COPY ~atweaks/spl/mephits/rr#msmsb.spl~ ~override~                                 // Sooty Ball (Smoke Mephit)
COPY ~atweaks/spl/mephits/rr#msmff.spl~ ~override~                                 // Flash of Flame (Smoke Mephit)
  SAY NAME1 @1857 SAY NAME2 @1857

COPY ~atweaks/spl/mephits/rr#mstgt.spl~ ~override~                                 // Gate (Steam Mephit)
COPY ~atweaks/eff/mephits/rr#mstgt.eff~ ~override~                                 // Gate EFF (Steam Mephit)
COPY ~atweaks/spl/mephits/rr#mstwj.spl~ ~override~                                 // Water Jet (Steam Mephit)
COPY ~atweaks/vvc/rr#mstbr.vvc~ ~override~                                         // Boiling Rain Storm animation (Mist Mephit)
COPY ~atweaks/spl/mephits/rr#mstbr.spl~ ~override~                                 // Boiling Rain Storm (Steam Mephit)



//////////////////
// Cloned spells
//////////////////


// Patch immunity to rr#mracs (Radiant Mephit Color Spray) into spells, items that cause blindness

COPY_EXISTING spdr101.spl  override
              spin595.spl  override
              spin878.spl  override
              spin893.spl  override
              spin929.spl  override
              spin931.spl  override
              sppr704.spl  override
              sppr707.spl  override
              spwi106.spl  override
              spwi118.spl  override
              spwi224.spl  override
              spwi714.spl  override
              spwi815.spl  override
              spwi958.spl  override
              spwm178.spl  override
              chalcy2.itm  override
              gorwom4.itm  override
              halb06.itm   override
              sorb.itm     override
              sw1h51.itm   override
              wand19.itm   override
  LPF add_conditional_immunity INT_VAR f_Condition = 74 STR_VAR f_Spell = rr#mracs END
BUT_ONLY

COPY_EXISTING ~SPWI112.SPL~  ~override/rr#wi112.spl~                               // Clone Magic Missile into an innate ability (Fire Mephit)
LAUNCH_PATCH_FUNCTION ~RR#SP2IN~ INT_VAR "rr#ctime" = "1" "rr#rinvs" = "1" END     // Execute the "spell to innate ablity" function

COPY_EXISTING ~SPWI201.SPL~  ~override/rr#wi201.spl~                               // Clone Blur into an innate ability (Air Mephit)
LAUNCH_PATCH_FUNCTION ~RR#SP2IN~ INT_VAR "rr#ctime" = "1" END                      // Execute the "spell to innate ablity" function

COPY_EXISTING ~SPWI206.SPL~  ~override/rr#wi206.spl~                               // Clone Invisibility into an innate ability (Smoke Mephit)
LAUNCH_PATCH_FUNCTION ~RR#SP2IN~ INT_VAR "rr#ctime" = "1" END                      // Execute the "spell to innate ablity" function

COPY_EXISTING ~SPWI213.SPL~  ~override/rr#mozsc.spl~                               // Clone Stinking Cloud into an innate ability (Ooze Mephit, special version)
LAUNCH_PATCH_FUNCTION ~RR#SP2IN~ INT_VAR "rr#ctime" = "1" "rr#rinvs" = "1" END     // Execute the "spell to innate ablity" function

COPY_EXISTING ~SPWI224.SPL~  ~override/rr#wi224.spl~                               // Clone Glitterdust into an innate ability (Mineral Mephit)
LAUNCH_PATCH_FUNCTION ~RR#SP2IN~ INT_VAR "rr#ctime" = "1" "rr#rinvs" = "1" END     // Execute the "spell to innate ablity" function



/////////////
// New items
/////////////

COPY ~atweaks/itm/mephits/rr#mrg1t.itm~ ~override~                                 // Mephit regeneration (1hp/turn)
COPY ~atweaks/itm/mephits/rr#mimun.itm~ ~override~                                 // Mephit immunities amulet (shared by all mephits)
PATCH_FOR_EACH ~spell~ IN                                                          // for each of the following spells
            ~SPPR103~                                                              // Cure Light Wounds
            ~SPPR215~                                                              // Cure Medium Wounds
            ~SPPR315~                                                              // Cure Medium Wounds
            ~SPPR401~                                                              // Cure Serious Wounds
            ~SPPR404~                                                              // Neutralize Poison
            ~SPPR502~                                                              // Cure Critical Wounds
            ~SPPR514~                                                              // Mass Cure
            ~SPPR514~                                                              // Mass Cure
            ~SPPR607~                                                              // Heal
            ~SPIN101~                                                              // Cure Light Wounds (Bhaalpower)
            ~SPIN551~                                                              // Cause Serious Wounds (Hive Mother)
            ~SPIN986~                                                              // Cause Serious Wounds (Beholder)
            ~SPCL211~                                                              // Paladin Lay On Hands
           ~RR#MOZSC~                                                              // Stinking Cloud (aTweaks' Ooze Mephit)
           ~RR#MDUGD~                                                              // Glass Dust (aTweaks' Dust Mephit)
BEGIN                                                                              // execute the following
LAUNCH_PATCH_FUNCTION ~ADD_ITEM_EQEFFECT~                                          // add new equipping effect
INT_VAR                                                                            // initialize variables
"opcode" = "206"                                                                   // effect: #206 (Protection from Spell)
"target" = "1"                                                                     // target: 1 (self)
"timing" = "2"                                                                     // timing mode: 2 (while equipped)
"duration" = "0"                                                                   // duration: 0
"parameter1" = "4742"                                                              // param1: string (Spell Ineffective)
"probability1" = "100"                                                             // probability1: 100%
STR_VAR                                                                            // initialize strings
"resource"  = EVALUATE_BUFFER "%spell%"                                            // resref: the current spell
END                                                                                // ends FUNCTION
END                                                                                // ends PATCH_FOR_EACH block
BUT_ONLY_IF_IT_CHANGES                                                   


COPY ~atweaks/itm/mephits/rr#mgasi.itm~ ~override~                                 // gas imunity ring (shared by several mephits)
PATCH_FOR_EACH ~spell~ IN                                                          // for each of the following spells
            ~SPWI004~                                                              // Stinking Cloud (trap)
            ~SPWI016~                                                              // Cloudkill (trap)
            ~SPWI213~                                                              // Stinking Cloud
            ~SPWI502~                                                              // Cloudkill
            ~SPWI614~                                                              // Death Fog
            ~SPWI810~                                                              // Incendiary Cloud
            ~SPIN940~                                                              // Stinking Cloud (mephit)
            ~SPIN979~                                                              // Golem Gas Cloud
            ~SPIN642~                                                              // Poisonous Cloud
           ~RR#WI502~                                                              // aTweaks' Cloudkill (used by Marilith)
           ~RR#MMSWF~                                                              // Wall of Fog (aTweaks' Mist Mephit)
BEGIN                                                                              // execute the following
LAUNCH_PATCH_FUNCTION ~ADD_ITEM_EQEFFECT~                                          // add new equipping effect
INT_VAR                                                                            // initialize variables
"opcode" = "206"                                                                   // effect: #206 (Protection from Spell)
"target" = "1"                                                                     // target: 1 (self)
"timing" = "2"                                                                     // timing mode: 2 (while equipped)
"duration" = "0"                                                                   // duration: 0
"parameter1" = "4742"                                                              // param1: string (Spell Ineffective)
"probability1" = "100"                                                             // probability1: 100%
STR_VAR                                                                            // initialize strings
"resource"  = EVALUATE_BUFFER "%spell%"                                            // resref: the current spell
END                                                                                // ends FUNCTION
END                                                                                // ends PATCH_FOR_EACH block
BUT_ONLY_IF_IT_CHANGES                                                   


COPY ~atweaks/itm/mephits/rr#maiw1.itm~ ~override~                                 // Air Mephit melee attack and special traits
COPY ~atweaks/itm/mephits/rr#mduw1.itm~ ~override~                                 // Dust Mephit melee attack and special traits
COPY ~atweaks/itm/mephits/rr#meaw1.itm~ ~override~                                 // Earth Mephit melee attack and special traits
COPY ~atweaks/itm/mephits/rr#meaw1.itm~ ~override/rr#meaw2.itm~                    // spawn Earth Mephit's second melee attack (Grow ability result)
READ_LONG 0x64 abil_off
READ_SHORT 0x68 abil_num
FOR (i = 0; i < "%abil_num%"; i += 1) BEGIN                                        // parse each ability
  READ_BYTE (%abil_off% + %i% * 0x38) abil_type                                    // read ability type
  PATCH_IF (%abil_type% = 1) BEGIN                                                 // only patch the melee ability header
    WRITE_SHORT ("%abil_off%" + 0x16) 6                                            // damage dice
    WRITE_SHORT ("%abil_off%" + 0x18) 2                                            // dice rolls
  END
END
COPY ~atweaks/itm/mephits/rr#mfiw1.itm~ ~override~                                 // Fire Mephit melee attack and special traits
COPY ~atweaks/itm/mephits/rr#micw1.itm~ ~override~                                 // Ice Mephit melee attack and special traits
COPY ~atweaks/itm/mephits/rr#mliw1.itm~ ~override~                                 // Lightning Mephit melee attack and special traits
COPY ~atweaks/itm/mephits/rr#mmaw1.itm~ ~override~                                 // Magma Mephit melee attack and special traits
COPY ~atweaks/itm/mephits/rr#mmiw1.itm~ ~override~                                 // Mineral Mephit melee attack and special traits
COPY ~atweaks/itm/mephits/rr#mmsw1.itm~ ~override~                                 // Mist Mephit melee attack and special traits
COPY ~atweaks/itm/mephits/rr#mozw1.itm~ ~override~                                 // Ooze Mephit melee attack and special traits
COPY ~atweaks/itm/mephits/rr#mraw1.itm~ ~override~                                 // Radiant Mephit melee attack and special traits
COPY ~atweaks/itm/mephits/rr#msaw1.itm~ ~override~                                 // Salt Mephit melee attack and special traits
COPY ~atweaks/itm/mephits/rr#msmw1.itm~ ~override~                                 // Smoke Mephit melee attack and special traits
COPY ~atweaks/itm/mephits/rr#mstw1.itm~ ~override~                                 // Steam Mephit melee attack and special traits









//////////////////////////
// Creature modifications
//////////////////////////


// Air Mephit

ACTION_FOR_EACH ~file~ IN                                                          // for each of the following files
            ~MEPAIR01~                                                             // Air Mephit
BEGIN                                                                              // execute the following
ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN                                   // if the file exists
COPY_EXISTING ~%file%.cre~ ~override~
LAUNCH_PATCH_FUNCTION FJ_CRE_VALIDITY INT_VAR do_message = 1 END                   // Nythrun's CRE validity macro (detects corrupt and invalid CREs)
// =============================================================================== // the actual work starts from here
REPLACE_CRE_ITEM ~RR#MAIW1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP                 // replace default weapon with a more PnP accurate weapon
REPLACE_CRE_ITEM ~RR#MRG1T~ #0 #0 #0 ~UNDROPPABLE~ ~LRING~                         // replace generic regeneration item with aTweaks' version
ADD_CRE_ITEM ~RR#MIMUN~ #0 #0 #0 ~UNDROPPABLE~ ~AMULET~                            // add aTweaks' shared mephit immunities
ADD_CRE_ITEM ~RR#MGASI~ #0 #0 #0 ~UNDROPPABLE~ ~RRING~                             // add aTweaks' immunity to gas-based spells
REMOVE_CRE_ITEM ~MOVRAT10~                                                         // removes MOVRAT10.ITM (movement rate is handled via the weapon)
REMOVE_CRE_ITEM ~REGHP1~                                                           // removes REGHP1.ITM (mephit regeneration is handled differently in aTweaks)
REMOVE_CRE_ITEM ~IMMCLOUD~                                                         // removes IMMCLOUD.ITM (immunity to cloud spells is handled differently)
REMOVE_KNOWN_SPELLS                                                                // Remove all known spells from the current creature
REMOVE_MEMORIZED_SPELLS                                                            // Remove all memorized spells from the current creature
LAUNCH_PATCH_FUNCTION ~RR#MDCRE~                                                   // Starts FUNCTION call (aTweaks' Creature Modification function)
INT_VAR                                                                            // Initialize variables
"newxpv"   = "420"                                                                 // new XP value
"newhp"    = "24"                                                                  // new hit point value
"newac"    = "4"                                                                   // new Armor Class value
"newth"    = "17"                                                                  // new THAC0 value
"newapr"   = "2"                                                                   // new number of attacks per round
"newsvd"   = "13"                                                                  // new Save vs. Death
"newsvw"   = "15"                                                                  // new Save vs. Wand
"newsvp"   = "14"                                                                  // new Save vs. Polymorph
"newsvb"   = "16"                                                                  // new Save vs. Breath
"newsvs"   = "16"                                                                  // new Save vs. Spell
"newlvl1"  = "3"                                                                   // new level (first class)
"newstr"   = "10"                                                                  // new Strength value
"newint"   = "10"                                                                  // new Intelligence value
"newwis"   = "11"                                                                  // new Wisdom value
"newdex"   = "14"                                                                  // new Dexterity value
"newcon"   = "10"                                                                  // new Constitution value
"newchr"   = "15"                                                                  // new Charisma value
"newmor"   = "10"                                                                  // new morale value
"newmorb"  = "4"                                                                   // new morale break value
"newmorr"  = "15"                                                                  // new morale recovery value
"newrace"  = "139"                                                                 // new race (Mephit)
"newalign" = "34"                                                                  // new alignment (True Neutral)
STR_VAR                                                                            // initialize strings
"enfc01"   = "MEPAIR01"                                                            // enforced creature 1 (uses strict PnP values)
END                                                                                // ends FUNCTION call
LAUNCH_PATCH_FUNCTION ~RR#MDCSC~                                                   // Starts FUNCTION call (aTweaks' Creature Script Modification function)
STR_VAR                                                                            // Initialize strings
"newscript"  = "RR#MAIR"                                                           // new AI script
"script01"   = ""                                                                  // first AI script name
"script02"   = "None"                                                              // second AI script name
"script03"   = "WTASIGHT"                                                          // third AI script name
"script04"   = "GENSHT01"                                                          // generic shout script
"script05"   = "BPWDASGT"                                                          // Big Picture script
"script06"   = "DW#MELEE"                                                          // SCSII melee script
"script07"   = "MEPAIR"                                                            // original Air Mephit script
"script08"   = "HUMANSHT"                                                          // Big Picture shout script
END                                                                                // ends FUNCTION call
// =============================================================================== // the actual work ends here
BUT_ONLY_IF_IT_CHANGES
END                                                                                // ends ACTION_IF FILE_EXISTS_IN_GAME block
END                                                                                // ends ACTION_FOR_EACH block



// Dust Mephit

ACTION_FOR_EACH ~file~ IN                                                          // for each of the following files
              ~MEPDUS01~                                                           // Dust Mephit
              ~ELEMEP08~                                                           // Dust Mephit
//              ~MDDUST~                                                           // Dust Mephit (unused?, don't process)
BEGIN                                                                              // execute the following
ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN                                   // if the file exists
COPY_EXISTING ~%file%.cre~ ~override~
LAUNCH_PATCH_FUNCTION FJ_CRE_VALIDITY INT_VAR do_message = 1 END                   // Nythrun's CRE validity macro (detects corrupt and invalid CREs)
// =============================================================================== // the actual work starts from here
REPLACE_CRE_ITEM ~RR#MDUW1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP                 // replace default weapon with a more PnP accurate weapon
REPLACE_CRE_ITEM ~RR#MRG1T~ #0 #0 #0 ~UNDROPPABLE~ ~LRING~                         // replace generic regeneration item with aTweaks' version
ADD_CRE_ITEM ~RR#MIMUN~ #0 #0 #0 ~UNDROPPABLE~ ~AMULET~                            // add aTweaks' shared mephit immunities
REMOVE_CRE_ITEM ~MOVRAT10~                                                         // removes MOVRAT10.ITM (movement rate is handled via the weapon)
REMOVE_CRE_ITEM ~REGHP1~                                                           // removes REGHP1.ITM (mephit regeneration is handled differently in aTweaks)
REMOVE_CRE_ITEM ~IMMCLOUD~                                                         // removes IMMCLOUD.ITM (immunity to cloud spells is handled differently)
REMOVE_KNOWN_SPELLS                                                                // Remove all known spells from the current creature
REMOVE_MEMORIZED_SPELLS                                                            // Remove all memorized spells from the current creature
LAUNCH_PATCH_FUNCTION ~RR#MDCRE~                                                   // Starts FUNCTION call (aTweaks' Creature Modification function)
INT_VAR                                                                            // Initialize variables
"newxpv"   = "420"                                                                 // new XP value
"newhp"    = "24"                                                                  // new hit point value
"newac"    = "6"                                                                   // new Armor Class value
"newth"    = "17"                                                                  // new THAC0 value
"newapr"   = "2"                                                                   // new number of attacks per round
"newsvd"   = "13"                                                                  // new Save vs. Death
"newsvw"   = "15"                                                                  // new Save vs. Wand
"newsvp"   = "14"                                                                  // new Save vs. Polymorph
"newsvb"   = "16"                                                                  // new Save vs. Breath
"newsvs"   = "16"                                                                  // new Save vs. Spell
"newfr"    = "100"                                                                 // new Resist Fire value
"newrs"    = "50"                                                                  // new Resist Slashing
"newrp"    = "50"                                                                  // new Resist Piercing
"newrm"    = "50"                                                                  // new Resist Missiles
"newlvl1"  = "3"                                                                   // new level (first class)
"newstr"   = "10"                                                                  // new Strength value
"newint"   = "10"                                                                  // new Intelligence value
"newwis"   = "11"                                                                  // new Wisdom value
"newdex"   = "14"                                                                  // new Dexterity value
"newcon"   = "10"                                                                  // new Constitution value
"newchr"   = "15"                                                                  // new Charisma value
"newmor"   = "10"                                                                  // new morale value
"newmorb"  = "4"                                                                   // new morale break value
"newmorr"  = "15"                                                                  // new morale recovery value
"newrace"  = "139"                                                                 // new race (Mephit)
"newalign" = "34"                                                                  // new alignment (True Neutral)
STR_VAR                                                                            // initialize strings
"enfc01"   = "MEPDUS01"                                                            // enforced creature 1 (uses strict PnP values)
"enfc02"   = "ELEMEP08"                                                            // enforced creature 2 (uses strict PnP values)
END                                                                                // ends FUNCTION call
LAUNCH_PATCH_FUNCTION ~RR#MDCSC~                                                   // Starts FUNCTION call (aTweaks' Creature Script Modification function)
STR_VAR                                                                            // Initialize strings
"newscript"  = "RR#MDUS"                                                           // new AI script
"script01"   = ""                                                                  // first AI script name
"script02"   = "None"                                                              // second AI script name
"script03"   = "WTASIGHT"                                                          // third AI script name
"script04"   = "GENSHT01"                                                          // generic shout script
"script05"   = "BPWDASGT"                                                          // Big Picture script
"script06"   = "DW#MELEE"                                                          // SCSII melee script
"script07"   = "MEPDUS"                                                            // original Dust Mephit script
"script08"   = "HUMANSHT"                                                          // Big Picture shout script
END                                                                                // ends FUNCTION call
// =============================================================================== // the actual work ends here
BUT_ONLY_IF_IT_CHANGES
END                                                                                // ends ACTION_IF FILE_EXISTS_IN_GAME block
END                                                                                // ends ACTION_FOR_EACH block



// Earth Mephit

ACTION_FOR_EACH ~file~ IN                                                          // for each of the following files
              ~MEPEAR01~                                                           // Earth Mephit
              ~ELEMEP06~                                                           // Earth Mephit
BEGIN                                                                              // execute the following
ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN                                   // if the file exists
COPY_EXISTING ~%file%.cre~ ~override~
LAUNCH_PATCH_FUNCTION FJ_CRE_VALIDITY INT_VAR do_message = 1 END                   // Nythrun's CRE validity macro (detects corrupt and invalid CREs)
// =============================================================================== // the actual work starts from here
REPLACE_CRE_ITEM ~RR#MEAW1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP                 // replace default weapon with a more PnP accurate weapon
REPLACE_CRE_ITEM ~RR#MRG1T~ #0 #0 #0 ~UNDROPPABLE~ ~LRING~                         // replace generic regeneration item with aTweaks' version
ADD_CRE_ITEM ~RR#MIMUN~ #0 #0 #0 ~UNDROPPABLE~ ~AMULET~                            // add aTweaks' shared mephit immunities
REMOVE_CRE_ITEM ~MOVRAT10~                                                         // removes MOVRAT10.ITM (movement rate is handled via the weapon)
REMOVE_CRE_ITEM ~REGHP1~                                                           // removes REGHP1.ITM (mephit regeneration is handled differently in aTweaks)
REMOVE_CRE_ITEM ~IMMCLOUD~                                                         // removes IMMCLOUD.ITM (immunity to cloud spells is handled differently)
REMOVE_KNOWN_SPELLS                                                                // Remove all known spells from the current creature
REMOVE_MEMORIZED_SPELLS                                                            // Remove all memorized spells from the current creature
LAUNCH_PATCH_FUNCTION ~RR#MDCRE~                                                   // Starts FUNCTION call (aTweaks' Creature Modification function)
INT_VAR                                                                            // Initialize variables
"newxpv"   = "420"                                                                 // new XP value
"newhp"    = "26"                                                                  // new hit point value
"newac"    = "5"                                                                   // new Armor Class value
"newth"    = "17"                                                                  // new THAC0 value
"newapr"   = "2"                                                                   // new number of attacks per round
"newsvd"   = "13"                                                                  // new Save vs. Death
"newsvw"   = "15"                                                                  // new Save vs. Wand
"newsvp"   = "14"                                                                  // new Save vs. Polymorph
"newsvb"   = "16"                                                                  // new Save vs. Breath
"newsvs"   = "16"                                                                  // new Save vs. Spell
"newlvl1"  = "3"                                                                   // new level (first class)
"newstr"   = "14"                                                                  // new Strength value
"newint"   = "9"                                                                   // new Intelligence value
"newwis"   = "11"                                                                  // new Wisdom value
"newdex"   = "10"                                                                  // new Dexterity value
"newcon"   = "13"                                                                  // new Constitution value
"newchr"   = "11"                                                                  // new Charisma value
"newmor"   = "10"                                                                  // new morale value
"newmorb"  = "4"                                                                   // new morale break value
"newmorr"  = "15"                                                                  // new morale recovery value
"newrace"  = "139"                                                                 // new race (Mephit)
"newalign" = "34"                                                                  // new alignment (True Neutral)
STR_VAR                                                                            // initialize strings
"enfc01"   = "MEPEAR01"                                                            // enforced creature 1 (uses strict PnP values)
"enfc02"   = "ELEMEP06"                                                            // enforced creature 2 (uses strict PnP values)
END                                                                                // ends FUNCTION call
LAUNCH_PATCH_FUNCTION ~RR#MDCSC~                                                   // Starts FUNCTION call (aTweaks' Creature Script Modification function)
STR_VAR                                                                            // Initialize strings
"newscript"  = "RR#MEAR"                                                           // new AI script
"script01"   = ""                                                                  // first AI script name
"script02"   = "None"                                                              // second AI script name
"script03"   = "WTASIGHT"                                                          // third AI script name
"script04"   = "GENSHT01"                                                          // generic shout script
"script05"   = "BPWDASGT"                                                          // Big Picture script
"script06"   = "DW#MELEE"                                                          // SCSII melee script
"script07"   = "MEPEAR"                                                            // original Earth Mephit script
"script08"   = "HUMANSHT"                                                          // Big Picture shout script
END                                                                                // ends FUNCTION call
// =============================================================================== // the actual work ends here
BUT_ONLY_IF_IT_CHANGES
END                                                                                // ends ACTION_IF FILE_EXISTS_IN_GAME block
END                                                                                // ends ACTION_FOR_EACH block



// Fire Mephit

ACTION_FOR_EACH ~file~ IN                                                          // for each of the following files
              ~MEPFIR01~                                                           // Fire Mephit
              ~ELEMEP04~                                                           // Fire Mephit
              ~OBSFIR02~                                                           // Fire Mephit
BEGIN                                                                              // execute the following
ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN                                   // if the file exists
COPY_EXISTING ~%file%.cre~ ~override~
LAUNCH_PATCH_FUNCTION FJ_CRE_VALIDITY INT_VAR do_message = 1 END                   // Nythrun's CRE validity macro (detects corrupt and invalid CREs)
// =============================================================================== // the actual work starts from here
REPLACE_CRE_ITEM ~RR#MFIW1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP                 // replace default weapon with a more PnP accurate weapon
ADD_CRE_ITEM ~RR#MIMUN~ #0 #0 #0 ~UNDROPPABLE~ ~AMULET~                            // add aTweaks' shared mephit immunities
REMOVE_CRE_ITEM ~MOVRAT10~                                                         // removes MOVRAT10.ITM (movement rate is handled via the weapon)
REMOVE_CRE_ITEM ~REGHP1~                                                           // removes REGHP1.ITM (mephit regeneration is handled differently in aTweaks)
REMOVE_CRE_ITEM ~IMMCLOUD~                                                         // removes IMMCLOUD.ITM (immunity to cloud spells is handled differently)
REMOVE_KNOWN_SPELLS                                                                // Remove all known spells from the current creature
REMOVE_MEMORIZED_SPELLS                                                            // Remove all memorized spells from the current creature
LAUNCH_PATCH_FUNCTION ~RR#MDCRE~                                                   // Starts FUNCTION call (aTweaks' Creature Modification function)
INT_VAR                                                                            // Initialize variables
"newxpv"   = "420"                                                                 // new XP value
"newhp"    = "25"                                                                  // new hit point value
"newac"    = "5"                                                                   // new Armor Class value
"newth"    = "17"                                                                  // new THAC0 value
"newapr"   = "2"                                                                   // new number of attacks per round
"newsvd"   = "13"                                                                  // new Save vs. Death
"newsvw"   = "15"                                                                  // new Save vs. Wand
"newsvp"   = "14"                                                                  // new Save vs. Polymorph
"newsvb"   = "16"                                                                  // new Save vs. Breath
"newsvs"   = "16"                                                                  // new Save vs. Spell
"newfr"    = "127"                                                                 // new Resist Fire value
"newlvl1"  = "3"                                                                   // new level (first class)
"newstr"   = "10"                                                                  // new Strength value
"newint"   = "10"                                                                  // new Intelligence value
"newwis"   = "11"                                                                  // new Wisdom value
"newdex"   = "13"                                                                  // new Dexterity value
"newcon"   = "10"                                                                  // new Constitution value
"newchr"   = "15"                                                                  // new Charisma value
"newmor"   = "10"                                                                  // new morale value
"newmorb"  = "4"                                                                   // new morale break value
"newmorr"  = "15"                                                                  // new morale recovery value
"newrace"  = "139"                                                                 // new race (Mephit)
"newalign" = "34"                                                                  // new alignment (True Neutral)
STR_VAR                                                                            // initialize strings
"enfc01"   = "MEPFIR01"                                                            // enforced creature 1 (uses strict PnP values)
"enfc02"   = "ELEMEP04"                                                            // enforced creature 2 (uses strict PnP values)
"enfc03"   = "OBSFIR02"                                                            // enforced creature 3 (uses strict PnP values)
END                                                                                // ends FUNCTION call
LAUNCH_PATCH_FUNCTION ~RR#MDCSC~                                                   // Starts FUNCTION call (aTweaks' Creature Script Modification function)
STR_VAR                                                                            // Initialize strings
"newscript"  = "RR#MFIR"                                                           // new AI script
"script01"   = ""                                                                  // first AI script name
"script02"   = "None"                                                              // second AI script name
"script03"   = "WTASIGHT"                                                          // third AI script name
"script04"   = "GENSHT01"                                                          // generic shout script
"script05"   = "BPWDASGT"                                                          // Big Picture script
"script06"   = "DW#MELEE"                                                          // SCSII melee script
"script07"   = "MEPFIR"                                                            // original Fire Mephit script
"script08"   = "HUMANSHT"                                                          // Big Picture shout script
END                                                                                // ends FUNCTION call
// =============================================================================== // the actual work ends here
BUT_ONLY_IF_IT_CHANGES
END                                                                                // ends ACTION_IF FILE_EXISTS_IN_GAME block
END                                                                                // ends ACTION_FOR_EACH block


// Ice Mephit

ACTION_FOR_EACH ~file~ IN                                                          // for each of the following files
              ~MEPICE01~                                                           // Ice Mephit
              ~MEPICE02~                                                           // Ice Mephit
              ~OBSICE02~                                                           // Ice Mephit
BEGIN                                                                              // execute the following
ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN                                   // if the file exists
COPY_EXISTING ~%file%.cre~ ~override~
LAUNCH_PATCH_FUNCTION FJ_CRE_VALIDITY INT_VAR do_message = 1 END                   // Nythrun's CRE validity macro (detects corrupt and invalid CREs)
// =============================================================================== // the actual work starts from here
REPLACE_CRE_ITEM ~RR#MICW1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP                 // replace default weapon with a more PnP accurate weapon
ADD_CRE_ITEM ~RR#MIMUN~ #0 #0 #0 ~UNDROPPABLE~ ~AMULET~                            // add aTweaks' shared mephit immunities
REMOVE_CRE_ITEM ~MOVRAT10~                                                         // removes MOVRAT10.ITM (movement rate is handled via the weapon)
REMOVE_CRE_ITEM ~REGHP1~                                                           // removes REGHP1.ITM (mephit regeneration is handled differently in aTweaks)
REMOVE_CRE_ITEM ~IMMCLOUD~                                                         // removes IMMCLOUD.ITM (immunity to cloud spells is handled differently)
REMOVE_KNOWN_SPELLS                                                                // Remove all known spells from the current creature
REMOVE_MEMORIZED_SPELLS                                                            // Remove all memorized spells from the current creature
LAUNCH_PATCH_FUNCTION ~RR#MDCRE~                                                   // Starts FUNCTION call (aTweaks' Creature Modification function)
INT_VAR                                                                            // Initialize variables
"newxpv"   = "420"                                                                 // new XP value
"newhp"    = "24"                                                                  // new hit point value
"newac"    = "5"                                                                   // new Armor Class value
"newth"    = "17"                                                                  // new THAC0 value
"newapr"   = "2"                                                                   // new number of attacks per round
"newsvd"   = "13"                                                                  // new Save vs. Death
"newsvw"   = "15"                                                                  // new Save vs. Wand
"newsvp"   = "14"                                                                  // new Save vs. Polymorph
"newsvb"   = "16"                                                                  // new Save vs. Breath
"newsvs"   = "16"                                                                  // new Save vs. Spell
"newfr"    = "0"                                                                   // new Resist Fire value
"newcr"    = "127"                                                                 // new Resist Cold value
"newlvl1"  = "3"                                                                   // new level (first class)
"newstr"   = "10"                                                                  // new Strength value
"newint"   = "10"                                                                  // new Intelligence value
"newwis"   = "11"                                                                  // new Wisdom value
"newdex"   = "14"                                                                  // new Dexterity value
"newcon"   = "10"                                                                  // new Constitution value
"newchr"   = "15"                                                                  // new Charisma value
"newmor"   = "10"                                                                  // new morale value
"newmorb"  = "4"                                                                   // new morale break value
"newmorr"  = "15"                                                                  // new morale recovery value
"newrace"  = "139"                                                                 // new race (Mephit)
"newalign" = "34"                                                                  // new alignment (True Neutral)
STR_VAR                                                                            // initialize strings
"enfc01"   = "MEPICE01"                                                            // enforced creature 1 (uses strict PnP values)
"enfc02"   = "MEPICE02"                                                            // enforced creature 2 (uses strict PnP values)
"enfc03"   = "OBSICE02"                                                            // enforced creature 3 (uses strict PnP values)
END                                                                                // ends FUNCTION call
LAUNCH_PATCH_FUNCTION ~RR#MDCSC~                                                   // Starts FUNCTION call (aTweaks' Creature Script Modification function)
STR_VAR                                                                            // Initialize strings
"newscript"  = "RR#MICE"                                                           // new AI script
"script01"   = ""                                                                  // first AI script name
"script02"   = "None"                                                              // second AI script name
"script03"   = "WTASIGHT"                                                          // third AI script name
"script04"   = "GENSHT01"                                                          // generic shout script
"script05"   = "BPWDASGT"                                                          // Big Picture script
"script06"   = "DW#MELEE"                                                          // SCSII melee script
"script07"   = "MEPICE"                                                            // original Ice Mephit script
"script08"   = "HUMANSHT"                                                          // Big Picture shout script
END                                                                                // ends FUNCTION call
// =============================================================================== // the actual work ends here
BUT_ONLY_IF_IT_CHANGES
END                                                                                // ends ACTION_IF FILE_EXISTS_IN_GAME block
END                                                                                // ends ACTION_FOR_EACH block



// Lightning Mephit

ACTION_FOR_EACH ~file~ IN                                                          // for each of the following files
              ~MEPLIG01~                                                           // Lightning Mephit
BEGIN                                                                              // execute the following
ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN                                   // if the file exists
COPY_EXISTING ~%file%.cre~ ~override~
LAUNCH_PATCH_FUNCTION FJ_CRE_VALIDITY INT_VAR do_message = 1 END                   // Nythrun's CRE validity macro (detects corrupt and invalid CREs)
// =============================================================================== // the actual work starts from here
REPLACE_CRE_ITEM ~RR#MLIW1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP                 // replace default weapon with a more PnP accurate weapon
ADD_CRE_ITEM ~RR#MIMUN~ #0 #0 #0 ~UNDROPPABLE~ ~AMULET~                            // add aTweaks' shared mephit immunities
REMOVE_CRE_ITEM ~MOVRAT10~                                                         // removes MOVRAT10.ITM (movement rate is handled via the weapon)
REMOVE_CRE_ITEM ~REGHP1~                                                           // removes REGHP1.ITM (mephit regeneration is handled differently in aTweaks)
REMOVE_CRE_ITEM ~IMMCLOUD~                                                         // removes IMMCLOUD.ITM (immunity to cloud spells is handled differently)
REMOVE_KNOWN_SPELLS                                                                // Remove all known spells from the current creature
REMOVE_MEMORIZED_SPELLS                                                            // Remove all memorized spells from the current creature
LAUNCH_PATCH_FUNCTION ~RR#MDCRE~                                                   // Starts FUNCTION call (aTweaks' Creature Modification function)
INT_VAR                                                                            // Initialize variables
"newxpv"   = "420"                                                                 // new XP value
"newhp"    = "24"                                                                  // new hit point value
"newac"    = "4"                                                                   // new Armor Class value
"newth"    = "17"                                                                  // new THAC0 value
"newapr"   = "2"                                                                   // new number of attacks per round
"newsvd"   = "13"                                                                  // new Save vs. Death
"newsvw"   = "15"                                                                  // new Save vs. Wand
"newsvp"   = "14"                                                                  // new Save vs. Polymorph
"newsvb"   = "16"                                                                  // new Save vs. Breath
"newsvs"   = "16"                                                                  // new Save vs. Spell
"newfr"    = "100"                                                                 // new Resist Fire value
"newer"    = "127"                                                                 // new Resist Electricity value
"newlvl1"  = "3"                                                                   // new level (first class)
"newstr"   = "10"                                                                  // new Strength value
"newint"   = "10"                                                                  // new Intelligence value
"newwis"   = "11"                                                                  // new Wisdom value
"newdex"   = "14"                                                                  // new Dexterity value
"newcon"   = "10"                                                                  // new Constitution value
"newchr"   = "15"                                                                  // new Charisma value
"newmor"   = "10"                                                                  // new morale value
"newmorb"  = "4"                                                                   // new morale break value
"newmorr"  = "15"                                                                  // new morale recovery value
"newrace"  = "139"                                                                 // new race (Mephit)
"newalign" = "34"                                                                  // new alignment (True Neutral)
STR_VAR                                                                            // initialize strings
"enfc01"   = "MEPLIG01"                                                            // enforced creature 1 (uses strict PnP values)
END                                                                                // ends FUNCTION call
LAUNCH_PATCH_FUNCTION ~RR#MDCSC~                                                   // Starts FUNCTION call (aTweaks' Creature Script Modification function)
STR_VAR                                                                            // Initialize strings
"newscript"  = "RR#MLIG"                                                           // new AI script
"script01"   = ""                                                                  // first AI script name
"script02"   = "None"                                                              // second AI script name
"script03"   = "WTASIGHT"                                                          // third AI script name
"script04"   = "GENSHT01"                                                          // generic shout script
"script05"   = "BPWDASGT"                                                          // Big Picture script
"script06"   = "DW#MELEE"                                                          // SCSII melee script
"script07"   = "MEPLIG"                                                            // original Lightning Mephit script
"script08"   = "HUMANSHT"                                                          // Big Picture shout script
END                                                                                // ends FUNCTION call
// =============================================================================== // the actual work ends here
BUT_ONLY_IF_IT_CHANGES
END                                                                                // ends ACTION_IF FILE_EXISTS_IN_GAME block
END                                                                                // ends ACTION_FOR_EACH block



// Magma Mephit

ACTION_FOR_EACH ~file~ IN                                                          // for each of the following files
              ~MEPMAG01~                                                           // Magma Mephit
              ~MEPMAG02~                                                           // Magma Mephit
              ~ELEMEP05~                                                           // Magma Mephit
              ~OBSFIR03~                                                           // Magma Mephit
BEGIN                                                                              // execute the following
ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN                                   // if the file exists
COPY_EXISTING ~%file%.cre~ ~override~
LAUNCH_PATCH_FUNCTION FJ_CRE_VALIDITY INT_VAR do_message = 1 END                   // Nythrun's CRE validity macro (detects corrupt and invalid CREs)
// =============================================================================== // the actual work starts from here
REPLACE_CRE_ITEM ~RR#MMAW1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP                 // replace default weapon with a more PnP accurate weapon
ADD_CRE_ITEM ~RR#MIMUN~ #0 #0 #0 ~UNDROPPABLE~ ~AMULET~                            // add aTweaks' shared mephit immunities
REMOVE_CRE_ITEM ~MOVRAT10~                                                         // removes MOVRAT10.ITM (movement rate is handled via the weapon)
REMOVE_CRE_ITEM ~REGHP1~                                                           // removes REGHP1.ITM (mephit regeneration is handled differently in aTweaks)
REMOVE_CRE_ITEM ~IMMCLOUD~                                                         // removes IMMCLOUD.ITM (immunity to cloud spells is handled differently)
REMOVE_KNOWN_SPELLS                                                                // Remove all known spells from the current creature
REMOVE_MEMORIZED_SPELLS                                                            // Remove all memorized spells from the current creature
LAUNCH_PATCH_FUNCTION ~RR#MDCRE~                                                   // Starts FUNCTION call (aTweaks' Creature Modification function)
INT_VAR                                                                            // Initialize variables
"newxpv"   = "420"                                                                 // new XP value
"newhp"    = "24"                                                                  // new hit point value
"newac"    = "6"                                                                   // new Armor Class value
"newth"    = "17"                                                                  // new THAC0 value
"newapr"   = "2"                                                                   // new number of attacks per round
"newsvd"   = "13"                                                                  // new Save vs. Death
"newsvw"   = "15"                                                                  // new Save vs. Wand
"newsvp"   = "14"                                                                  // new Save vs. Polymorph
"newsvb"   = "16"                                                                  // new Save vs. Breath
"newsvs"   = "16"                                                                  // new Save vs. Spell
"newfr"    = "127"                                                                 // new Resist Fire value
"newlvl1"  = "3"                                                                   // new level (first class)
"newstr"   = "10"                                                                  // new Strength value
"newint"   = "7"                                                                   // new Intelligence value
"newwis"   = "11"                                                                  // new Wisdom value
"newdex"   = "13"                                                                  // new Dexterity value
"newcon"   = "10"                                                                  // new Constitution value
"newchr"   = "15"                                                                  // new Charisma value
"newmor"   = "10"                                                                  // new morale value
"newmorb"  = "4"                                                                   // new morale break value
"newmorr"  = "15"                                                                  // new morale recovery value
"newrace"  = "139"                                                                 // new race (Mephit)
"newalign" = "34"                                                                  // new alignment (True Neutral)
STR_VAR                                                                            // initialize strings
"enfc01"   = "MEPMAG01"                                                            // enforced creature 1 (uses strict PnP values)
"enfc02"   = "MEPMAG02"                                                            // enforced creature 2 (uses strict PnP values)
"enfc03"   = "ELEMEP05"                                                            // enforced creature 3 (uses strict PnP values)
"enfc04"   = "OBSFIR03"                                                            // enforced creature 4 (uses strict PnP values)
END                                                                                // ends FUNCTION call
LAUNCH_PATCH_FUNCTION ~RR#MDCSC~                                                   // Starts FUNCTION call (aTweaks' Creature Script Modification function)
STR_VAR                                                                            // Initialize strings
"newscript"  = "RR#MMAG"                                                           // new AI script
"script01"   = ""                                                                  // first AI script name
"script02"   = "None"                                                              // second AI script name
"script03"   = "WTASIGHT"                                                          // third AI script name
"script04"   = "GENSHT01"                                                          // generic shout script
"script05"   = "BPWDASGT"                                                          // Big Picture script
"script06"   = "DW#MELEE"                                                          // SCSII melee script
"script07"   = "MEPMAG"                                                            // original Magma Mephit script
"script08"   = "HUMANSHT"                                                          // Big Picture shout script
END                                                                                // ends FUNCTION call
// =============================================================================== // the actual work ends here
BUT_ONLY_IF_IT_CHANGES
END                                                                                // ends ACTION_IF FILE_EXISTS_IN_GAME block
END                                                                                // ends ACTION_FOR_EACH block



// Mineral Mephit

ACTION_FOR_EACH ~file~ IN                                                          // for each of the following files
              ~MEPMIN01~                                                           // Mineral Mephit
              ~ELEMEP07~                                                           // Mineral Mephit
BEGIN                                                                              // execute the following
ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN                                   // if the file exists
COPY_EXISTING ~%file%.cre~ ~override~
LAUNCH_PATCH_FUNCTION FJ_CRE_VALIDITY INT_VAR do_message = 1 END                   // Nythrun's CRE validity macro (detects corrupt and invalid CREs)
// =============================================================================== // the actual work starts from here
REPLACE_CRE_ITEM ~RR#MMIW1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP                 // replace default weapon with a more PnP accurate weapon
REPLACE_CRE_ITEM ~RR#MRG1T~ #0 #0 #0 ~UNDROPPABLE~ ~LRING~                         // replace generic regeneration item with aTweaks' version
ADD_CRE_ITEM ~RR#MIMUN~ #0 #0 #0 ~UNDROPPABLE~ ~AMULET~                            // add aTweaks' shared mephit immunities
ADD_CRE_ITEM ~RR#MGASI~ #0 #0 #0 ~UNDROPPABLE~ ~RRING~                             // add aTweaks' immunity to gas-based spells
REMOVE_CRE_ITEM ~MOVRAT10~                                                         // removes MOVRAT10.ITM (movement rate is handled via the weapon)
REMOVE_CRE_ITEM ~REGHP1~                                                           // removes REGHP1.ITM (mephit regeneration is handled differently in aTweaks)
REMOVE_CRE_ITEM ~IMMCLOUD~                                                         // removes IMMCLOUD.ITM (immunity to cloud spells is handled differently)
REMOVE_KNOWN_SPELLS                                                                // Remove all known spells from the current creature
REMOVE_MEMORIZED_SPELLS                                                            // Remove all memorized spells from the current creature
LAUNCH_PATCH_FUNCTION ~RR#MDCRE~                                                   // Starts FUNCTION call (aTweaks' Creature Modification function)
INT_VAR                                                                            // Initialize variables
"newxpv"   = "420"                                                                 // new XP value
"newhp"    = "26"                                                                  // new hit point value
"newac"    = "4"                                                                   // new Armor Class value
"newth"    = "17"                                                                  // new THAC0 value
"newapr"   = "2"                                                                   // new number of attacks per round
"newsvd"   = "13"                                                                  // new Save vs. Death
"newsvw"   = "15"                                                                  // new Save vs. Wand
"newsvp"   = "14"                                                                  // new Save vs. Polymorph
"newsvb"   = "16"                                                                  // new Save vs. Breath
"newsvs"   = "16"                                                                  // new Save vs. Spell
"newrp"    = "100"                                                                 // new Resist Piercing
"newrm"    = "100"                                                                 // new Resist Missiles
"newlvl1"  = "3"                                                                   // new level (first class)
"newstr"   = "12"                                                                  // new Strength value
"newint"   = "10"                                                                  // new Intelligence value
"newwis"   = "11"                                                                  // new Wisdom value
"newdex"   = "12"                                                                  // new Dexterity value
"newcon"   = "12"                                                                  // new Constitution value
"newchr"   = "14"                                                                  // new Charisma value
"newmor"   = "10"                                                                  // new morale value
"newmorb"  = "4"                                                                   // new morale break value
"newmorr"  = "15"                                                                  // new morale recovery value
"newrace"  = "139"                                                                 // new race (Mephit)
"newalign" = "34"                                                                  // new alignment (True Neutral)
STR_VAR                                                                            // initialize strings
"enfc01"   = "MEPMIN01"                                                            // enforced creature 1 (uses strict PnP values)
"enfc02"   = "ELEMEP07"                                                            // enforced creature 2 (uses strict PnP values)
END                                                                                // ends FUNCTION call
LAUNCH_PATCH_FUNCTION ~RR#MDCSC~                                                   // Starts FUNCTION call (aTweaks' Creature Script Modification function)
STR_VAR                                                                            // Initialize strings
"newscript"  = "RR#MMIN"                                                           // new AI script
"script01"   = ""                                                                  // first AI script name
"script02"   = "None"                                                              // second AI script name
"script03"   = "WTASIGHT"                                                          // third AI script name
"script04"   = "GENSHT01"                                                          // generic shout script
"script05"   = "BPWDASGT"                                                          // Big Picture script
"script06"   = "DW#MELEE"                                                          // SCSII melee script
"script07"   = "MEPMIN"                                                            // original Air Mephit script
"script08"   = "HUMANSHT"                                                          // Big Picture shout script
END                                                                                // ends FUNCTION call
// =============================================================================== // the actual work ends here
BUT_ONLY_IF_IT_CHANGES
END                                                                                // ends ACTION_IF FILE_EXISTS_IN_GAME block
END                                                                                // ends ACTION_FOR_EACH block



// Mist Mephit

ACTION_FOR_EACH ~file~ IN                                                          // for each of the following files
              ~MEPMIS01~                                                           // Mist Mephit
               ~AR18FAM~                                                           // Mist Mephit
                ~GPFAM1~                                                           // Pitch
BEGIN                                                                              // execute the following
ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN                                   // if the file exists
COPY_EXISTING ~%file%.cre~ ~override~
LAUNCH_PATCH_FUNCTION FJ_CRE_VALIDITY INT_VAR do_message = 1 END                   // Nythrun's CRE validity macro (detects corrupt and invalid CREs)
// =============================================================================== // the actual work starts from here
REPLACE_CRE_ITEM ~RR#MMSW1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP                 // replace default weapon with a more PnP accurate weapon
ADD_CRE_ITEM ~RR#MIMUN~ #0 #0 #0 ~UNDROPPABLE~ ~AMULET~                            // add aTweaks' shared mephit immunities
REMOVE_CRE_ITEM ~MOVRAT10~                                                         // removes MOVRAT10.ITM (movement rate is handled via the weapon)
REMOVE_CRE_ITEM ~REGHP1~                                                           // removes REGHP1.ITM (mephit regeneration is handled differently in aTweaks)
REMOVE_CRE_ITEM ~IMMCLOUD~                                                         // removes IMMCLOUD.ITM (immunity to cloud spells is handled differently)
REMOVE_KNOWN_SPELLS                                                                // Remove all known spells from the current creature
REMOVE_MEMORIZED_SPELLS                                                            // Remove all memorized spells from the current creature
LAUNCH_PATCH_FUNCTION ~RR#MDCRE~                                                   // Starts FUNCTION call (aTweaks' Creature Modification function)
INT_VAR                                                                            // Initialize variables
"newxpv"   = "420"                                                                 // new XP value
"newhp"    = "26"                                                                  // new hit point value
"newac"    = "7"                                                                   // new Armor Class value
"newth"    = "17"                                                                  // new THAC0 value
"newapr"   = "2"                                                                   // new number of attacks per round
"newsvd"   = "13"                                                                  // new Save vs. Death
"newsvw"   = "15"                                                                  // new Save vs. Wand
"newsvp"   = "14"                                                                  // new Save vs. Polymorph
"newsvb"   = "16"                                                                  // new Save vs. Breath
"newsvs"   = "16"                                                                  // new Save vs. Spell
"newlvl1"  = "3"                                                                   // new level (first class)
"newstr"   = "10"                                                                  // new Strength value
"newint"   = "10"                                                                  // new Intelligence value
"newwis"   = "11"                                                                  // new Wisdom value
"newdex"   = "14"                                                                  // new Dexterity value
"newcon"   = "10"                                                                  // new Constitution value
"newchr"   = "15"                                                                  // new Charisma value
"newmor"   = "10"                                                                  // new morale value
"newmorb"  = "4"                                                                   // new morale break value
"newmorr"  = "15"                                                                  // new morale recovery value
"newrace"  = "139"                                                                 // new race (Mephit)
"newalign" = "34"                                                                  // new alignment (True Neutral)
STR_VAR                                                                            // initialize strings
"enfc01"   = "MEPMIS01"                                                            // enforced creature 1 (uses strict PnP values)
END                                                                                // ends FUNCTION call
LAUNCH_PATCH_FUNCTION ~RR#MDCSC~                                                   // Starts FUNCTION call (aTweaks' Creature Script Modification function)
STR_VAR                                                                            // Initialize strings
"newscript"  = "RR#MMST"                                                           // new AI script
"script01"   = ""                                                                  // first AI script name
"script02"   = "None"                                                              // second AI script name
"script03"   = "WTASIGHT"                                                          // third AI script name
"script04"   = "GENSHT01"                                                          // generic shout script
"script05"   = "BPWDASGT"                                                          // Big Picture script
"script06"   = "DW#MELEE"                                                          // SCSII melee script
"script07"   = "MEPMIS"                                                            // original Mist Mephit script
"script08"   = "GPMEPMIS"                                                          // group Mist Mephit script
"script09"   = "GPSHOUT"                                                           // group shout script
"script10"   = "HUMANSHT"                                                          // Big Picture shout script
"script11"   = "BPMEPMIS"                                                          // Big Picture Mist Mephit script
END                                                                                // ends FUNCTION call
// =============================================================================== // the actual work ends here
BUT_ONLY_IF_IT_CHANGES
END                                                                                // ends ACTION_IF FILE_EXISTS_IN_GAME block
END                                                                                // ends ACTION_FOR_EACH block



// Ooze Mephit

ACTION_FOR_EACH ~file~ IN                                                          // for each of the following files
              ~MEPOOZ01~                                                           // Ooze Mephit
              ~ELEMEP01~                                                           // Ooze Mephit
BEGIN                                                                              // execute the following
ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN                                   // if the file exists
COPY_EXISTING ~%file%.cre~ ~override~
LAUNCH_PATCH_FUNCTION FJ_CRE_VALIDITY INT_VAR do_message = 1 END                   // Nythrun's CRE validity macro (detects corrupt and invalid CREs)
// =============================================================================== // the actual work starts from here
REPLACE_CRE_ITEM ~RR#MOZW1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP                 // replace default weapon with a more PnP accurate weapon
REPLACE_CRE_ITEM ~RR#MRG1T~ #0 #0 #0 ~UNDROPPABLE~ ~LRING~                         // replace generic regeneration item with aTweaks' version
ADD_CRE_ITEM ~RR#MIMUN~ #0 #0 #0 ~UNDROPPABLE~ ~AMULET~                            // add aTweaks' shared mephit immunities
REMOVE_CRE_ITEM ~MOVRAT10~                                                         // removes MOVRAT10.ITM (movement rate is handled via the weapon)
REMOVE_CRE_ITEM ~REGHP1~                                                           // removes REGHP1.ITM (mephit regeneration is handled differently in aTweaks)
REMOVE_CRE_ITEM ~IMMCLOUD~                                                         // removes IMMCLOUD.ITM (immunity to cloud spells is handled differently)
REMOVE_KNOWN_SPELLS                                                                // Remove all known spells from the current creature
REMOVE_MEMORIZED_SPELLS                                                            // Remove all memorized spells from the current creature
LAUNCH_PATCH_FUNCTION ~RR#MDCRE~                                                   // Starts FUNCTION call (aTweaks' Creature Modification function)
INT_VAR                                                                            // Initialize variables
"newxpv"   = "420"                                                                 // new XP value
"newhp"    = "24"                                                                  // new hit point value
"newac"    = "6"                                                                   // new Armor Class value
"newth"    = "17"                                                                  // new THAC0 value
"newapr"   = "2"                                                                   // new number of attacks per round
"newsvd"   = "13"                                                                  // new Save vs. Death
"newsvw"   = "15"                                                                  // new Save vs. Wand
"newsvp"   = "14"                                                                  // new Save vs. Polymorph
"newsvb"   = "16"                                                                  // new Save vs. Breath
"newsvs"   = "16"                                                                  // new Save vs. Spell
"newfr"    = "100"                                                                 // new Resist Fire value
"newrs"    = "100"                                                                 // new Resist Slashing
"newrp"    = "100"                                                                 // new Resist Piercing
"newrm"    = "100"                                                                 // new Resist Missiles
"newlvl1"  = "3"                                                                   // new level (first class)
"newstr"   = "14"                                                                  // new Strength value
"newint"   = "10"                                                                  // new Intelligence value
"newwis"   = "11"                                                                  // new Wisdom value
"newdex"   = "10"                                                                  // new Dexterity value
"newcon"   = "13"                                                                  // new Constitution value
"newchr"   = "10"                                                                  // new Charisma value
"newmor"   = "7"                                                                   // new morale value
"newmorb"  = "4"                                                                   // new morale break value
"newmorr"  = "15"                                                                  // new morale recovery value
"newrace"  = "139"                                                                 // new race (Mephit)
"newalign" = "34"                                                                  // new alignment (True Neutral)
STR_VAR                                                                            // initialize strings
"enfc01"   = "MEPOOZ01"                                                            // enforced creature 1 (uses strict PnP values)
"enfc02"   = "ELEMEP01"                                                            // enforced creature 2 (uses strict PnP values)
END                                                                                // ends FUNCTION call
LAUNCH_PATCH_FUNCTION ~RR#MDCSC~                                                   // Starts FUNCTION call (aTweaks' Creature Script Modification function)
STR_VAR                                                                            // Initialize strings
"newscript"  = "RR#MOOZ"                                                           // new AI script
"script01"   = ""                                                                  // first AI script name
"script02"   = "None"                                                              // second AI script name
"script03"   = "WTASIGHT"                                                          // third AI script name
"script04"   = "GENSHT01"                                                          // generic shout script
"script05"   = "BPWDASGT"                                                          // Big Picture script
"script06"   = "DW#MELEE"                                                          // SCSII melee script
"script07"   = "MEPOOZ"                                                            // original Ooze Mephit script
"script08"   = "HUMANSHT"                                                          // Big Picture shout script
END                                                                                // ends FUNCTION call
// =============================================================================== // the actual work ends here
BUT_ONLY_IF_IT_CHANGES
END                                                                                // ends ACTION_IF FILE_EXISTS_IN_GAME block
END                                                                                // ends ACTION_FOR_EACH block



// Radiant Mephit

ACTION_FOR_EACH ~file~ IN                                                          // for each of the following files
              ~MEPRAD01~                                                           // Radiant Mephit
              ~MEPRAD02~                                                           // Radiant Mephit
BEGIN                                                                              // execute the following
ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN                                   // if the file exists
COPY_EXISTING ~%file%.cre~ ~override~
LAUNCH_PATCH_FUNCTION FJ_CRE_VALIDITY INT_VAR do_message = 1 END                   // Nythrun's CRE validity macro (detects corrupt and invalid CREs)
// =============================================================================== // the actual work starts from here
REPLACE_CRE_ITEM ~RR#MRAW1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP                 // replace default weapon with a more PnP accurate weapon
REPLACE_CRE_ITEM ~RR#MRG1T~ #0 #0 #0 ~UNDROPPABLE~ ~LRING~                         // replace generic regeneration item with aTweaks' version
ADD_CRE_ITEM ~RR#MIMUN~ #0 #0 #0 ~UNDROPPABLE~ ~AMULET~                            // add aTweaks' shared mephit immunities
REMOVE_CRE_ITEM ~MOVRAT10~                                                         // removes MOVRAT10.ITM (movement rate is handled via the weapon)
REMOVE_CRE_ITEM ~REGHP1~                                                           // removes REGHP1.ITM (mephit regeneration is handled differently in aTweaks)
REMOVE_CRE_ITEM ~IMMCLOUD~                                                         // removes IMMCLOUD.ITM (immunity to cloud spells is handled differently)
REMOVE_KNOWN_SPELLS                                                                // Remove all known spells from the current creature
REMOVE_MEMORIZED_SPELLS                                                            // Remove all memorized spells from the current creature
LAUNCH_PATCH_FUNCTION ~RR#MDCRE~                                                   // Starts FUNCTION call (aTweaks' Creature Modification function)
INT_VAR                                                                            // Initialize variables
"newxpv"   = "420"                                                                 // new XP value
"newhp"    = "24"                                                                  // new hit point value
"newac"    = "4"                                                                   // new Armor Class value
"newth"    = "17"                                                                  // new THAC0 value
"newapr"   = "2"                                                                   // new number of attacks per round
"newsvd"   = "13"                                                                  // new Save vs. Death
"newsvw"   = "15"                                                                  // new Save vs. Wand
"newsvp"   = "14"                                                                  // new Save vs. Polymorph
"newsvb"   = "16"                                                                  // new Save vs. Breath
"newsvs"   = "20"                                                                  // new Save vs. Spell
"newlvl1"  = "3"                                                                   // new level (first class)
"newstr"   = "10"                                                                  // new Strength value
"newint"   = "10"                                                                  // new Intelligence value
"newwis"   = "11"                                                                  // new Wisdom value
"newdex"   = "14"                                                                  // new Dexterity value
"newcon"   = "10"                                                                  // new Constitution value
"newchr"   = "15"                                                                  // new Charisma value
"newmor"   = "7"                                                                   // new morale value
"newmorb"  = "4"                                                                   // new morale break value
"newmorr"  = "15"                                                                  // new morale recovery value
"newrace"  = "139"                                                                 // new race (Mephit)
"newalign" = "34"                                                                  // new alignment (True Neutral)
STR_VAR                                                                            // initialize strings
"enfc01"   = "MEPRAD01"                                                            // enforced creature 1 (uses strict PnP values)
"enfc02"   = "MEPRAD02"                                                            // enforced creature 2 (uses strict PnP values)
END                                                                                // ends FUNCTION call
LAUNCH_PATCH_FUNCTION ~RR#MDCSC~                                                   // Starts FUNCTION call (aTweaks' Creature Script Modification function)
STR_VAR                                                                            // Initialize strings
"newscript"  = "RR#MRAD"                                                           // new AI script
"script01"   = ""                                                                  // first AI script name
"script02"   = "None"                                                              // second AI script name
"script03"   = "WTASIGHT"                                                          // third AI script name
"script04"   = "GENSHT01"                                                          // generic shout script
"script05"   = "BPWDASGT"                                                          // Big Picture script
"script06"   = "DW#MELEE"                                                          // SCSII melee script
"script07"   = "MEPRAD"                                                            // original Radiant Mephit script
"script08"   = "HUMANSHT"                                                          // Big Picture shout script
END                                                                                // ends FUNCTION call
// =============================================================================== // the actual work ends here
BUT_ONLY_IF_IT_CHANGES
END                                                                                // ends ACTION_IF FILE_EXISTS_IN_GAME block
END                                                                                // ends ACTION_FOR_EACH block


// Salt Mephit

ACTION_FOR_EACH ~file~ IN                                                          // for each of the following files
              ~MEPSAL01~                                                           // Salt Mephit
              ~ELEMEP03~                                                           // Salt Mephit
BEGIN                                                                              // execute the following
ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN                                   // if the file exists
COPY_EXISTING ~%file%.cre~ ~override~
LAUNCH_PATCH_FUNCTION FJ_CRE_VALIDITY INT_VAR do_message = 1 END                   // Nythrun's CRE validity macro (detects corrupt and invalid CREs)
// =============================================================================== // the actual work starts from here
REPLACE_CRE_ITEM ~RR#MSAW1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP                 // replace default weapon with a more PnP accurate weapon
REPLACE_CRE_ITEM ~RR#MRG1T~ #0 #0 #0 ~UNDROPPABLE~ ~LRING~                         // replace generic regeneration item with aTweaks' version
ADD_CRE_ITEM ~RR#MIMUN~ #0 #0 #0 ~UNDROPPABLE~ ~AMULET~                            // add aTweaks' shared mephit immunities
REMOVE_CRE_ITEM ~MOVRAT10~                                                         // removes MOVRAT10.ITM (movement rate is handled via the weapon)
REMOVE_CRE_ITEM ~REGHP1~                                                           // removes REGHP1.ITM (mephit regeneration is handled differently in aTweaks)
REMOVE_CRE_ITEM ~IMMCLOUD~                                                         // removes IMMCLOUD.ITM (immunity to cloud spells is handled differently)
REMOVE_KNOWN_SPELLS                                                                // Remove all known spells from the current creature
REMOVE_MEMORIZED_SPELLS                                                            // Remove all memorized spells from the current creature
LAUNCH_PATCH_FUNCTION ~RR#MDCRE~                                                   // Starts FUNCTION call (aTweaks' Creature Modification function)
INT_VAR                                                                            // Initialize variables
"newxpv"   = "420"                                                                 // new XP value
"newhp"    = "24"                                                                  // new hit point value
"newac"    = "6"                                                                   // new Armor Class value
"newth"    = "17"                                                                  // new THAC0 value
"newapr"   = "2"                                                                   // new number of attacks per round
"newsvd"   = "13"                                                                  // new Save vs. Death
"newsvw"   = "15"                                                                  // new Save vs. Wand
"newsvp"   = "14"                                                                  // new Save vs. Polymorph
"newsvb"   = "16"                                                                  // new Save vs. Breath
"newsvs"   = "16"                                                                  // new Save vs. Spell
"newfr"    = "100"                                                                 // new Resist Fire value
"newlvl1"  = "3"                                                                   // new level (first class)
"newstr"   = "10"                                                                  // new Strength value
"newint"   = "10"                                                                  // new Intelligence value
"newwis"   = "11"                                                                  // new Wisdom value
"newdex"   = "14"                                                                  // new Dexterity value
"newcon"   = "10"                                                                  // new Constitution value
"newchr"   = "15"                                                                  // new Charisma value
"newmor"   = "10"                                                                  // new morale value
"newmorb"  = "4"                                                                   // new morale break value
"newmorr"  = "15"                                                                  // new morale recovery value
"newrace"  = "139"                                                                 // new race (Mephit)
"newalign" = "34"                                                                  // new alignment (True Neutral)
STR_VAR                                                                            // initialize strings
"enfc01"   = "MEPSAL01"                                                            // enforced creature 1 (uses strict PnP values)
"enfc02"   = "ELEMEP03"                                                            // enforced creature 2 (uses strict PnP values)
END                                                                                // ends FUNCTION call
LAUNCH_PATCH_FUNCTION ~RR#MDCSC~                                                   // Starts FUNCTION call (aTweaks' Creature Script Modification function)
STR_VAR                                                                            // Initialize strings
"newscript"  = "RR#MSAL"                                                           // new AI script
"script01"   = ""                                                                  // first AI script name
"script02"   = "None"                                                              // second AI script name
"script03"   = "WTASIGHT"                                                          // third AI script name
"script04"   = "GENSHT01"                                                          // generic shout script
"script05"   = "BPWDASGT"                                                          // Big Picture script
"script06"   = "DW#MELEE"                                                          // SCSII melee script
"script07"   = "MEPSAL"                                                            // original Salt Mephit script
"script08"   = "HUMANSHT"                                                          // Big Picture shout script
END                                                                                // ends FUNCTION call
// =============================================================================== // the actual work ends here
BUT_ONLY_IF_IT_CHANGES
END                                                                                // ends ACTION_IF FILE_EXISTS_IN_GAME block
END                                                                                // ends ACTION_FOR_EACH block


// Smoke Mephit

ACTION_FOR_EACH ~file~ IN                                                          // for each of the following files
              ~MEPSMO01~                                                           // Smoke Mephit
              ~MEPSMO02~                                                           // Smoke Mephit
              ~OBSFIR04~                                                           // Smoke Mephit
BEGIN                                                                              // execute the following
ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN                                   // if the file exists
COPY_EXISTING ~%file%.cre~ ~override~
LAUNCH_PATCH_FUNCTION FJ_CRE_VALIDITY INT_VAR do_message = 1 END                   // Nythrun's CRE validity macro (detects corrupt and invalid CREs)
// =============================================================================== // the actual work starts from here
REPLACE_CRE_ITEM ~RR#MSMW1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP                 // replace default weapon with a more PnP accurate weapon
REPLACE_CRE_ITEM ~RR#MRG1T~ #0 #0 #0 ~UNDROPPABLE~ ~LRING~                         // replace generic regeneration item with aTweaks' version
ADD_CRE_ITEM ~RR#MIMUN~ #0 #0 #0 ~UNDROPPABLE~ ~AMULET~                            // add aTweaks' shared mephit immunities
REMOVE_CRE_ITEM ~MOVRAT10~                                                         // removes MOVRAT10.ITM (movement rate is handled via the weapon)
REMOVE_CRE_ITEM ~REGHP1~                                                           // removes REGHP1.ITM (mephit regeneration is handled differently in aTweaks)
REMOVE_CRE_ITEM ~IMMCLOUD~                                                         // removes IMMCLOUD.ITM (immunity to cloud spells is handled differently)
REMOVE_KNOWN_SPELLS                                                                // Remove all known spells from the current creature
REMOVE_MEMORIZED_SPELLS                                                            // Remove all memorized spells from the current creature
LAUNCH_PATCH_FUNCTION ~RR#MDCRE~                                                   // Starts FUNCTION call (aTweaks' Creature Modification function)
INT_VAR                                                                            // Initialize variables
"newxpv"   = "420"                                                                 // new XP value
"newhp"    = "24"                                                                  // new hit point value
"newac"    = "4"                                                                   // new Armor Class value
"newth"    = "17"                                                                  // new THAC0 value
"newapr"   = "2"                                                                   // new number of attacks per round
"newsvd"   = "13"                                                                  // new Save vs. Death
"newsvw"   = "15"                                                                  // new Save vs. Wand
"newsvp"   = "14"                                                                  // new Save vs. Polymorph
"newsvb"   = "16"                                                                  // new Save vs. Breath
"newsvs"   = "16"                                                                  // new Save vs. Spell
"newlvl1"  = "3"                                                                   // new level (first class)
"newstr"   = "10"                                                                  // new Strength value
"newint"   = "10"                                                                  // new Intelligence value
"newwis"   = "11"                                                                  // new Wisdom value
"newdex"   = "14"                                                                  // new Dexterity value
"newcon"   = "10"                                                                  // new Constitution value
"newchr"   = "15"                                                                  // new Charisma value
"newmor"   = "10"                                                                  // new morale value
"newmorb"  = "4"                                                                   // new morale break value
"newmorr"  = "15"                                                                  // new morale recovery value
"newrace"  = "139"                                                                 // new race (Mephit)
"newalign" = "34"                                                                  // new alignment (True Neutral)
STR_VAR                                                                            // initialize strings
"enfc01"   = "MEPSMO01"                                                            // enforced creature 1 (uses strict PnP values)
"enfc02"   = "MEPSMO02"                                                            // enforced creature 2 (uses strict PnP values)
"enfc03"   = "OBSFIR04"                                                            // enforced creature 3 (uses strict PnP values)
END                                                                                // ends FUNCTION call
LAUNCH_PATCH_FUNCTION ~RR#MDCSC~                                                   // Starts FUNCTION call (aTweaks' Creature Script Modification function)
STR_VAR                                                                            // Initialize strings
"newscript"  = "RR#MSMO"                                                           // new AI script
"script01"   = ""                                                                  // first AI script name
"script02"   = "None"                                                              // second AI script name
"script03"   = "WTASIGHT"                                                          // third AI script name
"script04"   = "GENSHT01"                                                          // generic shout script
"script05"   = "BPWDASGT"                                                          // Big Picture script
"script06"   = "DW#MELEE"                                                          // SCSII melee script
"script07"   = "MEPSMO"                                                            // original Smoke Mephit script
"script08"   = "HUMANSHT"                                                          // Big Picture shout script
END                                                                                // ends FUNCTION call
// =============================================================================== // the actual work ends here
READ_LONG  0x10 "flags"                                                            // special case, Smoke Mephits should vanish upon death
WRITE_LONG 0x10 ("%flags%" BOR 0b00000010)                                         // add "no corpse" flag
BUT_ONLY_IF_IT_CHANGES
END                                                                                // ends ACTION_IF FILE_EXISTS_IN_GAME block
END                                                                                // ends ACTION_FOR_EACH block


// Smoke Mephit

ACTION_FOR_EACH ~file~ IN                                                          // for each of the following files
              ~MEPSTE01~                                                           // Steam Mephit
              ~ELEMEP02~                                                           // Steam Mephit
BEGIN                                                                              // execute the following
ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN                                   // if the file exists
COPY_EXISTING ~%file%.cre~ ~override~
LAUNCH_PATCH_FUNCTION FJ_CRE_VALIDITY INT_VAR do_message = 1 END                   // Nythrun's CRE validity macro (detects corrupt and invalid CREs)
// =============================================================================== // the actual work starts from here
REPLACE_CRE_ITEM ~RR#MSTW1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP                 // replace default weapon with a more PnP accurate weapon
ADD_CRE_ITEM ~RR#MIMUN~ #0 #0 #0 ~UNDROPPABLE~ ~AMULET~                            // add aTweaks' shared mephit immunities
REMOVE_CRE_ITEM ~MOVRAT10~                                                         // removes MOVRAT10.ITM (movement rate is handled via the weapon)
REMOVE_CRE_ITEM ~REGHP1~                                                           // removes REGHP1.ITM (mephit regeneration is handled differently in aTweaks)
REMOVE_CRE_ITEM ~IMMCLOUD~                                                         // removes IMMCLOUD.ITM (immunity to cloud spells is handled differently)
REMOVE_KNOWN_SPELLS                                                                // Remove all known spells from the current creature
REMOVE_MEMORIZED_SPELLS                                                            // Remove all memorized spells from the current creature
LAUNCH_PATCH_FUNCTION ~RR#MDCRE~                                                   // Starts FUNCTION call (aTweaks' Creature Modification function)
INT_VAR                                                                            // Initialize variables
"newxpv"   = "420"                                                                 // new XP value
"newhp"    = "27"                                                                  // new hit point value
"newac"    = "7"                                                                   // new Armor Class value
"newth"    = "17"                                                                  // new THAC0 value
"newapr"   = "2"                                                                   // new number of attacks per round
"newsvd"   = "13"                                                                  // new Save vs. Death
"newsvw"   = "15"                                                                  // new Save vs. Wand
"newsvp"   = "14"                                                                  // new Save vs. Polymorph
"newsvb"   = "16"                                                                  // new Save vs. Breath
"newsvs"   = "16"                                                                  // new Save vs. Spell
"newfr"    = "100"                                                                 // new Resist Fire value
"newlvl1"  = "3"                                                                   // new level (first class)
"newstr"   = "10"                                                                  // new Strength value
"newint"   = "10"                                                                  // new Intelligence value
"newwis"   = "11"                                                                  // new Wisdom value
"newdex"   = "13"                                                                  // new Dexterity value
"newcon"   = "10"                                                                  // new Constitution value
"newchr"   = "15"                                                                  // new Charisma value
"newmor"   = "10"                                                                  // new morale value
"newmorb"  = "1"                                                                   // new morale break value
"newmorr"  = "15"                                                                  // new morale recovery value
"newrace"  = "139"                                                                 // new race (Mephit)
"newalign" = "34"                                                                  // new alignment (True Neutral)
STR_VAR                                                                            // initialize strings
"enfc01"   = "MEPSTE01"                                                            // enforced creature 1 (uses strict PnP values)
"enfc02"   = "ELEMEP02"                                                            // enforced creature 2 (uses strict PnP values)
END                                                                                // ends FUNCTION call
LAUNCH_PATCH_FUNCTION ~RR#MDCSC~                                                   // Starts FUNCTION call (aTweaks' Creature Script Modification function)
STR_VAR                                                                            // Initialize strings
"newscript"  = "RR#MSTE"                                                           // new AI script
"script01"   = ""                                                                  // first AI script name
"script02"   = "None"                                                              // second AI script name
"script03"   = "WTASIGHT"                                                          // third AI script name
"script04"   = "GENSHT01"                                                          // generic shout script
"script05"   = "BPWDASGT"                                                          // Big Picture script
"script06"   = "DW#MELEE"                                                          // SCSII melee script
"script07"   = "MEPSTE"                                                            // original Steam Mephit script
"script08"   = "HUMANSHT"                                                          // Big Picture shout script
END                                                                                // ends FUNCTION call
// =============================================================================== // the actual work ends here
BUT_ONLY_IF_IT_CHANGES
END                                                                                // ends ACTION_IF FILE_EXISTS_IN_GAME block
END                                                                                // ends ACTION_FOR_EACH block



////////////////////////////
// Clone mephits for gating
////////////////////////////


COPY_EXISTING ~MEPAIR01.CRE~ ~override/RR#MAIR.CRE~                                // Air Mephit
              ~MEPDUS01.CRE~ ~override/RR#MDUS.CRE~                                // Dust Mephit
              ~MEPEAR01.CRE~ ~override/RR#MEAR.CRE~                                // Earth Mephit
              ~MEPFIR01.CRE~ ~override/RR#MFIR.CRE~                                // Fire Mephit
              ~MEPICE01.CRE~ ~override/RR#MICE.CRE~                                // Ice Mephit
              ~MEPLIG01.CRE~ ~override/RR#MLIG.CRE~                                // Lightning Mephit
              ~MEPMAG01.CRE~ ~override/RR#MMAG.CRE~                                // Magma Mephit
              ~MEPMIN01.CRE~ ~override/RR#MMIN.CRE~                                // Mineral Mephit
              ~MEPMIS01.CRE~ ~override/RR#MMST.CRE~                                // Mist Mephit
              ~MEPOOZ01.CRE~ ~override/RR#MOOZ.CRE~                                // Ooze Mephit
              ~MEPRAD01.CRE~ ~override/RR#MRAD.CRE~                                // Radiant Mephit
              ~MEPSAL01.CRE~ ~override/RR#MSAL.CRE~                                // Salt Mephit
              ~MEPSMO01.CRE~ ~override/RR#MSMO.CRE~                                // Smoke Mephit
              ~MEPSTE01.CRE~ ~override/RR#MSTE.CRE~                                // Steam Mephit
WRITE_BYTE 0x275 3                                                                 // set gender to other (serves as an identifier for gated mephits)



//////////////////
// New AI Scripts
//////////////////


COMPILE ~atweaks/baf/mephits/rr#mair.baf~                                          // Air Mephit AI script
COMPILE ~atweaks/baf/mephits/rr#mdus.baf~                                          // Dust Mephit AI script
COMPILE ~atweaks/baf/mephits/rr#mear.baf~                                          // Earth Mephit AI script
COMPILE ~atweaks/baf/mephits/rr#mfir.baf~                                          // Fire Mephit AI script
COMPILE ~atweaks/baf/mephits/rr#mice.baf~                                          // Ice Mephit AI script
COMPILE ~atweaks/baf/mephits/rr#mlig.baf~                                          // Lightning Mephit AI script
COMPILE ~atweaks/baf/mephits/rr#mmag.baf~                                          // Magma Mephit AI script
COMPILE ~atweaks/baf/mephits/rr#mmin.baf~                                          // Mineral Mephit AI script
COMPILE ~atweaks/baf/mephits/rr#mmst.baf~                                          // Mist Mephit AI script
COMPILE ~atweaks/baf/mephits/rr#mooz.baf~                                          // Ooze Mephit AI script
COMPILE ~atweaks/baf/mephits/rr#mrad.baf~                                          // Radiant Mephit AI script
COMPILE ~atweaks/baf/mephits/rr#msal.baf~                                          // Salt Mephit AI script
COMPILE ~atweaks/baf/mephits/rr#msmo.baf~                                          // Smoke Mephit AI script
COMPILE ~atweaks/baf/mephits/rr#mste.baf~                                          // Steam Mephit AI script




///////////////////////////////////
// More sensible mephit encounters
///////////////////////////////////


// In Rayic Gethras' home, fire and magma mephits are mixed with ice mephits
// Replace ice mephits with dust mephits who are immune to fire

COPY_EXISTING ~AR0315.ARE~ ~override~                                              // Rayic Gethras' home, ground floor
  REPLACE_TEXTUALLY CASE_INSENSITIVE "MEPICE01" "MEPSTE01"                         // replace Ice Mephits with Steam Mephits (note: name lengths must be the same)
BUT_ONLY_IF_IT_CHANGES


// In the the air room of Irenicus' dungeon, fire mephits are placed alongside non fire-resistant mephits so replace them with smoke mephits
// Also, replace one Mist Mephit with a Steam Mephit since mist and steam mephits don't get along very well

COPY_EXISTING ~AR0601.ARE~ ~override~                                              // Irenicus' dungeon, air room
  REPLACE_TEXTUALLY CASE_INSENSITIVE "MEPFIR01" "MEPSMO01"                         // replace Fire Mephits with Smoke Mephits (note: name lengths must be the same)
  READ_LONG  0x54 "actor_off"
  READ_SHORT 0x58 "actor_num"
  SET "mepmis" = 0
  WHILE ("%actor_num%" > 0) BEGIN
    SET "actor_num" = ("%actor_num%" - 1)
    READ_ASCII ("%actor_off%" + 0x80 + ("%actor_num%" * 0x110)) "cre_file"
    PATCH_IF ("%cre_file%" STRING_EQUAL_CASE "MEPMIS01") BEGIN
      PATCH_IF ("%mepmis%" = 0) BEGIN
        SET "mepmis" = 1
      END ELSE BEGIN
        WRITE_ASCII ("%actor_off%" +        ("%actor_num%" * 0x110)) ~Steam Mephit~ #32
        WRITE_ASCII ("%actor_off%" + 0x80 + ("%actor_num%" * 0x110)) ~MEPSTE01~ #8
      END
    END
  END
BUT_ONLY_IF_IT_CHANGES


// In the Spellhold maze, ice and smoke mephits are placed near a Rahshasa who usually kills them with a Cloudkill. 
// Replace them with air and mineral mephits who are immune to gas-based spells

COPY_EXISTING ~AR1512.ARE~ ~override~                                              // Spellhold maze
  REPLACE_TEXTUALLY CASE_INSENSITIVE "MEPICE01" "MEPMIN01"                         // replace Ice Mephit with Mineral Mephit (note: name lengths must be the same)
  REPLACE_TEXTUALLY CASE_INSENSITIVE "MEPSMO01" "MEPMIN01"                         // replace Smoke Mephit with Mineral Mephit (note: name lengths must be the same)
BUT_ONLY_IF_IT_CHANGES


// The random spawning 2DA handles mephits suboptimally
// Change it to spawn mephits which won't interfere with each other (i.e. they are all immune to each other's area-effect abilities)

COPY_EXISTING ~SPAWNGRP.2DA~ ~override~                                            // random monster group spawn table
  REPLACE_TEXTUALLY CASE_INSENSITIVE ~Mepair01~ ~Meplig01~                         // Replace Air Mephits with Lightning Mephits
  REPLACE_TEXTUALLY CASE_INSENSITIVE ~Mepice01~ ~Mepsal01~                         // Replace Ice Mephits with Salt Mephits
  REPLACE_TEXTUALLY CASE_INSENSITIVE ~Mepsmo01~ ~Mepste01~                         // Replace Smoke Mephits with Steam Mephits
BUT_ONLY_IF_IT_CHANGES



//////////////
// Misc stuff
//////////////

// A Shadow Thief and an Ice Mephit that are fighting in Irenicus' dungeon need special treatment

COPY_EXISTING ~ar0603.are~ ~override~
  READ_LONG  0x54 "actor_off"
  READ_SHORT 0x58 "actor_num"
  FOR (index = 0 ; index < actor_num ; index = index + 1) BEGIN
    READ_ASCII ("%actor_off%" + 0x80 + ("%index%" * 0x110)) "cre_file"
    PATCH_IF ("%cre_file%" STRING_COMPARE_CASE "mepice01" = 0) BEGIN               // ice mephit
      WRITE_ASCII ("%actor_off%" + 0x50 + ("%index%" * 0x110)) ~~ #8               // erase override script
      SET "index" = "%actor_num%" // kills loop
    END
  END
BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~ISHTHF01.CRE~ ~override~                                            // Shadow Thief
 WRITE_BYTE  0x270 128                                                             // set allegiance to NEUTRAL
BUT_ONLY_IF_IT_CHANGES

<<<<<<<<atweaks/inlined/baf/mephits/ishthf1.baf
IF
	Allegiance(Myself,NEUTRAL)
	Detect([PC])
THEN
	RESPONSE #100
		ChangeEnemyAlly(Myself,GOODBUTBLUE)
END
>>>>>>>>

EXTEND_TOP ~ISHTHF01.BCS~  ~atweaks/inlined/baf/mephits/ishthf1.baf~


// Mephit portals in Irenicus' dungeon spawn mephits on game reload even when they've been destroyed

COPY_EXISTING ~MEPHSP01.BCS~ ~override~                                            // Smoke Mephit portal script
              ~MEPHSP02.BCS~ ~override~                                            // Ice Mephit portal script
              ~MEPHSP03.BCS~ ~override~                                            // Magma Mephit portal script
              ~MEPHSP04.BCS~ ~override~                                            // Radiant Mephit portal script
 DECOMPILE_BCS_TO_BAF
  REPLACE_TEXTUALLY EXACT_MATCH ~See([PC])~ ~!StateCheck(Myself,STATE_REALLY_DEAD) See([PC])~
 COMPILE_BAF_TO_BCS
 BUT_ONLY_IF_IT_CHANGES 