DEFINE_PATCH_FUNCTION prep_for_gate_making BEGIN
  READ_LONG  0x64 ao
  READ_LONG  0x6a eo
  READ_SHORT 0x70 ei
  FOR (i=0;i<SHORT_AT 0x68;++i) BEGIN
    WRITE_SHORT ao + 0x28*i + 0x12 0 //casting time
    WRITE_SHORT ao + 0x28*i + 0x20 ei
    READ_SHORT  ao + 0x28*i + 0x1e ne
    FOR (j=0;j<ne;++j) BEGIN
      DELETE_BYTES eo + 0x30*(j + ei) 0x30
      --j
      --ne
    END
    WRITE_SHORT ao + 0x28*i + 0x1e ne
    ei += ne
  END
END
