
// Add ToB scripting actions/triggers to SoA (borrowed from the G3 BG2 Fixpack with thanks) 
INCLUDE ~atweaks/lib/tob2soa.tph~

COPY    ~aTweaks/SPL/RR#HOINF.SPL~ ~override~                                      // spell which grants permament infravision
EXTEND_BOTTOM ~dplayer3.bcs~  ~aTweaks/BAF/DPLAYER.BAF~                            // extend the party script for Player1
EXTEND_BOTTOM ~dplayer2.bcs~  ~aTweaks/BAF/DPLAYER.BAF~                            // extend the party script for other party members
