//This is for that mean-spirited behaviour

IF
  See([ANYONE])
  False()
THEN
  RESPONSE #100
    Continue()
END

IF
  Race(LastSeenBy(Myself),DEMONIC)
  Alignment(LastSeenBy(Myself),MASK_EVIL)
  Allegiance(Myself,GOODCUTOFF)
  !Allegiance(LastSeenBy(Myself),EVILCUTOFF)
THEN
  RESPONSE #100
    RandomWalkContinuous()
END

IF
  Race(LastSeenBy(Myself),DEMONIC)
  Alignment(LastSeenBy(Myself),MASK_EVIL)
  Allegiance(Myself,EVILCUTOFF)
  !Allegiance(LastSeenBy(Myself),GOODCUTOFF)
THEN
  RESPONSE #100
    RandomWalkContinuous()
END

IF
  General(LastSeenBy(Myself),UNDEAD)
  OR(2)
    Gender(LastSeenBy(Myself),SUMMONED)
    Gender(LastSeenBy(Myself),20
  Allegiance(Myself,GOODCUTOFF)
  !Allegiance(LastSeenBy(Myself),EVILCUTOFF)
THEN
  RESPONSE #100
    RandomWalkContinuous()
END

IF
  General(LastSeenBy(Myself),UNDEAD)
  OR(2)
    Gender(LastSeenBy(Myself),SUMMONED)
    Gender(LastSeenBy(Myself),20)
  Allegiance(Myself,EVILCUTOFF)
  !Allegiance(LastSeenBy(Myself),GOODCUTOFF)
THEN
  RESPONSE #100
    RandomWalkContinuous()
END

IF
  !Range(LastSeenBy(Myself),6)
  !GlobalTimerNotExpired("flCast","LOCALS")
  ActionListEmpty()
THEN
  RESPONSE #100
    ForceSpellRES("RR#TELWE",LastSeenBy(Myself))
    SetGlobalTimer("flCast","LOCALS",6)
END

IF
  ActionListEmpty()
THEN
  RESPONSE #100
    AttackOneRound(LastSeenBy(Myself))
END

