
IF TRIGGER
  TargetBlock(EnemiesInOrder)
  TriggerBlock(WeaponImmunity|SlashResFull)
  StateCheck(scstarget,STATE_IMMOBILE)
THEN DO
  AttackOneRound(scstarget)
END

IF TRIGGER
  TargetBlock(EnemiesInOrder)
  TriggerBlock(WeaponImmunity|SlashResFull|Stoneskin|MirrorImage|Disabled)
  !Range(scstarget,5)
THEN DO
  Action(ForceSpellRES,"RR#TELWE")
END

IF TRIGGER
  TargetBlock(EnemiesInOrder)
  TriggerBlock(WeaponImmunity|SlashResFull|Stoneskin|MirrorImage|Disabled)
THEN DO
  AttackOneRound(scstarget)
END 

IF TRIGGER
  TargetBlock(EnemiesInOrder)
  TriggerBlock(Disabled|WeaponImmunity|SlashResFull)
  !Range(scstarget,5)
THEN DO
  Action(ForceSpellRES,"RR#TELWE")
END

IF TRIGGER
  TargetBlock(EnemiesInOrder)
  TriggerBlock(Disabled|WeaponImmunity|SlashResFull)
THEN DO
  AttackOneRound(scstarget)
END

IF TRIGGER
  TargetBlock(EnemiesInOrder)
  TriggerBlock(WeaponImmunity|SlashResFull)
  !Range(scstarget,5)
THEN DO
  Action(ForceSpellRES,"RR#TELWE")
END

IF TRIGGER
  TargetBlock(EnemiesInOrder)
  TriggerBlock(WeaponImmunity|SlashResFull)
THEN DO
  AttackOneRound(scstarget)
END
