IF TRIGGER
  TargetBlock(PCsInOrder)
  TargetBlock(EnemiesInOrder)
  TriggerBlock(Disabled|Enemy|Stoneskin|WeaponImmunity|MirrorImage)
  !HPPercentGT(scstarget,25)
THEN DO
  Action(BeholderAttack)
END

IF TRIGGER
  TargetBlock(PCsInOrder)
  TargetBlock(EnemiesInOrder)
  TriggerBlock(Disabled|Enemy|Stoneskin|WeaponImmunity|MirrorImage)
  !HPPercentGT(scstarget,50)
THEN DO
  Action(BeholderAttack)
END

IF TRIGGER
  TargetBlock(PCsInOrder)
  TargetBlock(EnemiesInOrder)
  TriggerBlock(Disabled|Enemy|Stoneskin|WeaponImmunity|MirrorImage)
THEN DO
  Action(BeholderAttack)
END

IF TRIGGER
  !GlobalTimerNotExpired("flNotMove","LOCALS")
  TargetBlock(PCsInOrder)
  TargetBlock(EnemiesInOrder)
  TriggerBlock(Enemy|Stoneskin|MirrorImage|WeaponImmunity)
  OR(2)
    StateCheck(scstarget,STATE_DISABLED)
    CheckStatGT(scstarget,0,HELD)
  !StateCheck(scstarget,STATE_STONE_DEATH)
THEN DO
  Action(MoveIfEmpty)
END

IF TRIGGER
  TargetBlock(EnemiesInOrder)
  TriggerBlock(Enemy|Stoneskin|WeaponImmunity|MirrorImage)
  !StateCheck(scstarget,STATE_STONE_DEATH)
THEN DO
  Action(BeholderAttack)
END
