IF
  HitBy([ANYONE],0)
  DamageTakenGT(9)
  DamageTakenLT(15)
  RandomNum(6,1)
  Global("flDisabled1","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled1","LOCALS",1)
    DisplayStringHead(Myself,@1336)
    ReallyForceSpellRES("fl#h10",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(14)
  DamageTakenLT(20)
  RandomNum(6,1)
  Global("flDisabled1","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled1","LOCALS",1)
    DisplayStringHead(Myself,@1336)
    ReallyForceSpellRES("fl#h15",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(19)
  DamageTakenLT(25)
  RandomNum(6,1)
  Global("flDisabled1","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled1","LOCALS",1)
    DisplayStringHead(Myself,@1336)
    ReallyForceSpellRES("fl#h20",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(24)
  DamageTakenLT(30)
  RandomNum(6,1)
  Global("flDisabled1","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled1","LOCALS",1)
    DisplayStringHead(Myself,@1336)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(29)
  DamageTakenLT(35)
  RandomNum(6,1)
  Global("flDisabled1","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled1","LOCALS",1)
    DisplayStringHead(Myself,@1336)
    ReallyForceSpellRES("fl#h30",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(34)
  DamageTakenLT(40)
  RandomNum(6,1)
  Global("flDisabled1","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled1","LOCALS",1)
    DisplayStringHead(Myself,@1336)
    ReallyForceSpellRES("fl#h35",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(39)
  RandomNum(6,1)
  Global("flDisabled1","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled1","LOCALS",1)
    DisplayStringHead(Myself,@1336)
    ReallyForceSpellRES("fl#h40",Myself)
  RESPONSE #85
    Continue()
END



IF
  HitBy([ANYONE],0)
  DamageTakenGT(9)
  DamageTakenLT(15)
  RandomNum(6,2)
  Global("flDisabled2","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled2","LOCALS",1)
    DisplayStringHead(Myself,@1337)
    ReallyForceSpellRES("fl#h10",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(14)
  DamageTakenLT(20)
  RandomNum(6,2)
  Global("flDisabled2","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled2","LOCALS",1)
    DisplayStringHead(Myself,@1337)
    ReallyForceSpellRES("fl#h15",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(19)
  DamageTakenLT(25)
  RandomNum(6,2)
  Global("flDisabled2","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled2","LOCALS",1)
    DisplayStringHead(Myself,@1337)
    ReallyForceSpellRES("fl#h20",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(24)
  DamageTakenLT(30)
  RandomNum(6,2)
  Global("flDisabled2","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled2","LOCALS",1)
    DisplayStringHead(Myself,@1337)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(29)
  DamageTakenLT(35)
  RandomNum(6,2)
  Global("flDisabled2","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled2","LOCALS",1)
    DisplayStringHead(Myself,@1337)
    ReallyForceSpellRES("fl#h30",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(34)
  DamageTakenLT(40)
  RandomNum(6,2)
  Global("flDisabled2","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled2","LOCALS",1)
    DisplayStringHead(Myself,@1337)
    ReallyForceSpellRES("fl#h35",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(39)
  RandomNum(6,2)
  Global("flDisabled2","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled2","LOCALS",1)
    DisplayStringHead(Myself,@1337)
    ReallyForceSpellRES("fl#h40",Myself)
  RESPONSE #85
    Continue()
END



IF
  HitBy([ANYONE],0)
  DamageTakenGT(9)
  DamageTakenLT(15)
  RandomNum(6,3)
  Global("flDisabled3","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled3","LOCALS",1)
    DisplayStringHead(Myself,@1338)
    ReallyForceSpellRES("fl#h10",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(14)
  DamageTakenLT(20)
  RandomNum(6,3)
  Global("flDisabled3","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled3","LOCALS",1)
    DisplayStringHead(Myself,@1338)
    ReallyForceSpellRES("fl#h15",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(19)
  DamageTakenLT(25)
  RandomNum(6,3)
  Global("flDisabled3","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled3","LOCALS",1)
    DisplayStringHead(Myself,@1338)
    ReallyForceSpellRES("fl#h20",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(24)
  DamageTakenLT(30)
  RandomNum(6,3)
  Global("flDisabled3","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled3","LOCALS",1)
    DisplayStringHead(Myself,@1338)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(29)
  DamageTakenLT(35)
  RandomNum(6,3)
  Global("flDisabled3","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled3","LOCALS",1)
    DisplayStringHead(Myself,@1338)
    ReallyForceSpellRES("fl#h30",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(34)
  DamageTakenLT(40)
  RandomNum(6,3)
  Global("flDisabled3","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled3","LOCALS",1)
    DisplayStringHead(Myself,@1338)
    ReallyForceSpellRES("fl#h35",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(39)
  RandomNum(6,3)
  Global("flDisabled3","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled3","LOCALS",1)
    DisplayStringHead(Myself,@1338)
    ReallyForceSpellRES("fl#h40",Myself)
  RESPONSE #85
    Continue()
END



IF
  HitBy([ANYONE],0)
  DamageTakenGT(9)
  DamageTakenLT(15)
  RandomNum(6,4)
  Global("flDisabled4","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled4","LOCALS",1)
    DisplayStringHead(Myself,@1327)
    ReallyForceSpellRES("fl#h10",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(14)
  DamageTakenLT(20)
  RandomNum(6,4)
  Global("flDisabled4","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled4","LOCALS",1)
    DisplayStringHead(Myself,@1327)
    ReallyForceSpellRES("fl#h15",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(19)
  DamageTakenLT(25)
  RandomNum(6,4)
  Global("flDisabled4","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled4","LOCALS",1)
    DisplayStringHead(Myself,@1327)
    ReallyForceSpellRES("fl#h20",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(24)
  DamageTakenLT(30)
  RandomNum(6,4)
  Global("flDisabled4","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled4","LOCALS",1)
    DisplayStringHead(Myself,@1327)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(29)
  DamageTakenLT(35)
  RandomNum(6,4)
  Global("flDisabled4","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled4","LOCALS",1)
    DisplayStringHead(Myself,@1327)
    ReallyForceSpellRES("fl#h30",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(34)
  DamageTakenLT(40)
  RandomNum(6,4)
  Global("flDisabled4","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled4","LOCALS",1)
    DisplayStringHead(Myself,@1327)
    ReallyForceSpellRES("fl#h35",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(39)
  RandomNum(6,4)
  Global("flDisabled4","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled4","LOCALS",1)
    DisplayStringHead(Myself,@1327)
    ReallyForceSpellRES("fl#h40",Myself)
  RESPONSE #85
    Continue()
END



IF
  HitBy([ANYONE],0)
  DamageTakenGT(9)
  DamageTakenLT(15)
  RandomNum(6,5)
  Global("flDisabled5","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled5","LOCALS",1)
    DisplayStringHead(Myself,@1339)
    ReallyForceSpellRES("fl#h10",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(14)
  DamageTakenLT(20)
  RandomNum(6,5)
  Global("flDisabled5","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled5","LOCALS",1)
    DisplayStringHead(Myself,@1339)
    ReallyForceSpellRES("fl#h15",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(19)
  DamageTakenLT(25)
  RandomNum(6,5)
  Global("flDisabled5","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled5","LOCALS",1)
    DisplayStringHead(Myself,@1339)
    ReallyForceSpellRES("fl#h20",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(24)
  DamageTakenLT(30)
  RandomNum(6,5)
  Global("flDisabled5","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled5","LOCALS",1)
    DisplayStringHead(Myself,@1339)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(29)
  DamageTakenLT(35)
  RandomNum(6,5)
  Global("flDisabled5","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled5","LOCALS",1)
    DisplayStringHead(Myself,@1339)
    ReallyForceSpellRES("fl#h30",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(34)
  DamageTakenLT(40)
  RandomNum(6,5)
  Global("flDisabled5","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled5","LOCALS",1)
    DisplayStringHead(Myself,@1339)
    ReallyForceSpellRES("fl#h35",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(39)
  RandomNum(6,5)
  Global("flDisabled5","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled5","LOCALS",1)
    DisplayStringHead(Myself,@1339)
    ReallyForceSpellRES("fl#h40",Myself)
  RESPONSE #85
    Continue()
END



IF
  HitBy([ANYONE],0)
  DamageTakenGT(14)
  DamageTakenLT(20)
  RandomNum(6,6)
  Global("flDisabled6","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled6","LOCALS",1)
    DisplayStringHead(Myself,@1330)
    ReallyForceSpellRES("fl#bhdir",Myself)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(19)
  DamageTakenLT(25)
  RandomNum(6,6)
  Global("flDisabled6","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled6","LOCALS",1)
    DisplayStringHead(Myself,@1330)
    ReallyForceSpellRES("fl#bhdir",Myself)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(24)
  DamageTakenLT(30)
  RandomNum(6,6)
  Global("flDisabled6","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled6","LOCALS",1)
    DisplayStringHead(Myself,@1330)
    ReallyForceSpellRES("fl#bhdir",Myself)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(29)
  DamageTakenLT(35)
  RandomNum(6,6)
  Global("flDisabled6","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled6","LOCALS",1)
    DisplayStringHead(Myself,@1330)
    ReallyForceSpellRES("fl#bhdir",Myself)
    ReallyForceSpellRES("fl#h30",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(34)
  DamageTakenLT(40)
  RandomNum(6,6)
  Global("flDisabled6","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled6","LOCALS",1)
    DisplayStringHead(Myself,@1330)
    ReallyForceSpellRES("fl#bhdir",Myself)
    ReallyForceSpellRES("fl#h35",Myself)
  RESPONSE #85
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(39)
  RandomNum(6,6)
  Global("flDisabled6","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled6","LOCALS",1)
    DisplayStringHead(Myself,@1330)
    ReallyForceSpellRES("fl#bhdir",Myself)
    ReallyForceSpellRES("fl#h40",Myself)
  RESPONSE #85
    Continue()
END
