IF
  HitBy([ANYONE],0)
  DamageTakenGT(4)
  DamageTakenLT(10)
  RandomNum(7,1)
  Global("flDisabled1","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled1","LOCALS",1)
    DisplayStringHead(Myself,@1328)
    ReallyForceSpellRES("fl#h5",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(9)
  DamageTakenLT(15)
  RandomNum(7,1)
  Global("flDisabled1","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled1","LOCALS",1)
    DisplayStringHead(Myself,@1328)
    ReallyForceSpellRES("fl#h10",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(14)
  DamageTakenLT(20)
  RandomNum(7,1)
  Global("flDisabled1","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled1","LOCALS",1)
    DisplayStringHead(Myself,@1328)
    ReallyForceSpellRES("fl#h15",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(19)
  DamageTakenLT(25)
  RandomNum(7,1)
  Global("flDisabled1","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled1","LOCALS",1)
    DisplayStringHead(Myself,@1328)
    ReallyForceSpellRES("fl#h20",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(24)
  DamageTakenLT(30)
  RandomNum(7,1)
  Global("flDisabled1","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled1","LOCALS",1)
    DisplayStringHead(Myself,@1328)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(29)
  DamageTakenLT(35)
  RandomNum(7,1)
  Global("flDisabled1","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled1","LOCALS",1)
    DisplayStringHead(Myself,@1328)
    ReallyForceSpellRES("fl#h30",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(34)
  DamageTakenLT(40)
  RandomNum(7,1)
  Global("flDisabled1","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled1","LOCALS",1)
    DisplayStringHead(Myself,@1328)
    ReallyForceSpellRES("fl#h35",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(39)
  RandomNum(7,1)
  Global("flDisabled1","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled1","LOCALS",1)
    DisplayStringHead(Myself,@1328)
    ReallyForceSpellRES("fl#h40",Myself)
  RESPONSE #90
    Continue()
END



IF
  HitBy([ANYONE],0)
  DamageTakenGT(4)
  DamageTakenLT(10)
  RandomNum(7,2)
  Global("flDisabled2","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled2","LOCALS",1)
    DisplayStringHead(Myself,@1331)
    ReallyForceSpellRES("fl#h5",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(9)
  DamageTakenLT(15)
  RandomNum(7,2)
  Global("flDisabled2","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled2","LOCALS",1)
    DisplayStringHead(Myself,@1331)
    ReallyForceSpellRES("fl#h10",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(14)
  DamageTakenLT(20)
  RandomNum(7,2)
  Global("flDisabled2","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled2","LOCALS",1)
    DisplayStringHead(Myself,@1331)
    ReallyForceSpellRES("fl#h15",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(19)
  DamageTakenLT(25)
  RandomNum(7,2)
  Global("flDisabled2","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled2","LOCALS",1)
    DisplayStringHead(Myself,@1331)
    ReallyForceSpellRES("fl#h20",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(24)
  DamageTakenLT(30)
  RandomNum(7,2)
  Global("flDisabled2","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled2","LOCALS",1)
    DisplayStringHead(Myself,@1331)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(29)
  DamageTakenLT(35)
  RandomNum(7,2)
  Global("flDisabled2","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled2","LOCALS",1)
    DisplayStringHead(Myself,@1331)
    ReallyForceSpellRES("fl#h30",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(34)
  DamageTakenLT(40)
  RandomNum(7,2)
  Global("flDisabled2","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled2","LOCALS",1)
    DisplayStringHead(Myself,@1331)
    ReallyForceSpellRES("fl#h35",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(39)
  RandomNum(7,2)
  Global("flDisabled2","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled2","LOCALS",1)
    DisplayStringHead(Myself,@1331)
    ReallyForceSpellRES("fl#h40",Myself)
  RESPONSE #90
    Continue()
END



IF
  HitBy([ANYONE],0)
  DamageTakenGT(4)
  DamageTakenLT(10)
  RandomNum(7,3)
  Global("flDisabled3","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled3","LOCALS",1)
    DisplayStringHead(Myself,@1332)
    ReallyForceSpellRES("fl#h5",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(9)
  DamageTakenLT(15)
  RandomNum(7,3)
  Global("flDisabled3","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled3","LOCALS",1)
    DisplayStringHead(Myself,@1332)
    ReallyForceSpellRES("fl#h10",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(14)
  DamageTakenLT(20)
  RandomNum(7,3)
  Global("flDisabled3","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled3","LOCALS",1)
    DisplayStringHead(Myself,@1332)
    ReallyForceSpellRES("fl#h15",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(19)
  DamageTakenLT(25)
  RandomNum(7,3)
  Global("flDisabled3","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled3","LOCALS",1)
    DisplayStringHead(Myself,@1332)
    ReallyForceSpellRES("fl#h20",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(24)
  DamageTakenLT(30)
  RandomNum(7,3)
  Global("flDisabled3","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled3","LOCALS",1)
    DisplayStringHead(Myself,@1332)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(29)
  DamageTakenLT(35)
  RandomNum(7,3)
  Global("flDisabled3","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled3","LOCALS",1)
    DisplayStringHead(Myself,@1332)
    ReallyForceSpellRES("fl#h30",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(35)
  DamageTakenLT(40)
  RandomNum(7,3)
  Global("flDisabled3","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled3","LOCALS",1)
    DisplayStringHead(Myself,@1332)
    ReallyForceSpellRES("fl#h35",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(39)
  RandomNum(7,3)
  Global("flDisabled3","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled3","LOCALS",1)
    DisplayStringHead(Myself,@1332)
    ReallyForceSpellRES("fl#h40",Myself)
  RESPONSE #90
    Continue()
END



IF
  HitBy([ANYONE],0)
  DamageTakenGT(4)
  DamageTakenLT(10)
  RandomNum(7,4)
  Global("flDisabled4","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled4","LOCALS",1)
    DisplayStringHead(Myself,@1333)
    ReallyForceSpellRES("fl#h5",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(9)
  DamageTakenLT(15)
  RandomNum(7,4)
  Global("flDisabled4","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled4","LOCALS",1)
    DisplayStringHead(Myself,@1333)
    ReallyForceSpellRES("fl#h10",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(14)
  DamageTakenLT(20)
  RandomNum(7,4)
  Global("flDisabled4","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled4","LOCALS",1)
    DisplayStringHead(Myself,@1333)
    ReallyForceSpellRES("fl#h15",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(19)
  DamageTakenLT(25)
  RandomNum(7,4)
  Global("flDisabled4","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled4","LOCALS",1)
    DisplayStringHead(Myself,@1333)
    ReallyForceSpellRES("fl#h20",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(24)
  DamageTakenLT(30)
  RandomNum(7,4)
  Global("flDisabled4","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled4","LOCALS",1)
    DisplayStringHead(Myself,@1333)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(29)
  DamageTakenLT(35)
  RandomNum(7,4)
  Global("flDisabled4","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled4","LOCALS",1)
    DisplayStringHead(Myself,@1333)
    ReallyForceSpellRES("fl#h30",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(34)
  DamageTakenLT(40)
  RandomNum(7,4)
  Global("flDisabled4","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled4","LOCALS",1)
    DisplayStringHead(Myself,@1333)
    ReallyForceSpellRES("fl#h35",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(39)
  RandomNum(7,4)
  Global("flDisabled4","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled4","LOCALS",1)
    DisplayStringHead(Myself,@1333)
    ReallyForceSpellRES("fl#h40",Myself)
  RESPONSE #90
    Continue()
END



IF
  HitBy([ANYONE],0)
  DamageTakenGT(4)
  DamageTakenLT(10)
  RandomNum(7,5)
  Global("flDisabled5","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled5","LOCALS",1)
    DisplayStringHead(Myself,@1334)
    ReallyForceSpellRES("fl#h5",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(9)
  DamageTakenLT(15)
  RandomNum(7,5)
  Global("flDisabled5","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled5","LOCALS",1)
    DisplayStringHead(Myself,@1334)
    ReallyForceSpellRES("fl#h10",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(14)
  DamageTakenLT(20)
  RandomNum(7,5)
  Global("flDisabled5","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled5","LOCALS",1)
    DisplayStringHead(Myself,@1334)
    ReallyForceSpellRES("fl#h15",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(19)
  DamageTakenLT(25)
  RandomNum(7,5)
  Global("flDisabled5","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled5","LOCALS",1)
    DisplayStringHead(Myself,@1334)
    ReallyForceSpellRES("fl#h20",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(24)
  DamageTakenLT(30)
  RandomNum(7,5)
  Global("flDisabled5","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled5","LOCALS",1)
    DisplayStringHead(Myself,@1334)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(29)
  DamageTakenLT(35)
  RandomNum(7,5)
  Global("flDisabled5","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled5","LOCALS",1)
    DisplayStringHead(Myself,@1334)
    ReallyForceSpellRES("fl#h30",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(34)
  DamageTakenLT(40)
  RandomNum(7,5)
  Global("flDisabled5","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled5","LOCALS",1)
    DisplayStringHead(Myself,@1334)
    ReallyForceSpellRES("fl#h35",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(39)
  RandomNum(7,5)
  Global("flDisabled5","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled5","LOCALS",1)
    DisplayStringHead(Myself,@1334)
    ReallyForceSpellRES("fl#h40",Myself)
  RESPONSE #90
    Continue()
END



//IF
//  HitBy([ANYONE],0)
//  DamageTakenGT(15)
//  RandomNum(7,6)
//  Global("flDisabled6","LOCALS",0)
//  !StateCheck(Myself,STATE_REALLY_DEAD)
//THEN
//  RESPONSE #5
//    SetGlobal("flDisabled6","LOCALS",1)
//    DisplayStringHead(Myself,@1330)
//  RESPONSE #95
//    Continue()
//END



IF
  HitBy([ANYONE],0)
  DamageTakenGT(4)
  DamageTakenLT(10)
  RandomNum(7,7)
  Global("flDisabled7","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled7","LOCALS",1)
    DisplayStringHead(Myself,@1335)
    ReallyForceSpellRES("fl#h5",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(9)
  DamageTakenLT(15)
  RandomNum(7,7)
  Global("flDisabled7","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled7","LOCALS",1)
    DisplayStringHead(Myself,@1335)
    ReallyForceSpellRES("fl#h10",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(14)
  DamageTakenLT(20)
  RandomNum(7,7)
  Global("flDisabled7","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled7","LOCALS",1)
    DisplayStringHead(Myself,@1335)
    ReallyForceSpellRES("fl#h15",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(19)
  DamageTakenLT(25)
  RandomNum(7,7)
  Global("flDisabled7","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled7","LOCALS",1)
    DisplayStringHead(Myself,@1335)
    ReallyForceSpellRES("fl#h20",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(24)
  DamageTakenLT(30)
  RandomNum(7,7)
  Global("flDisabled7","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled7","LOCALS",1)
    DisplayStringHead(Myself,@1335)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(29)
  DamageTakenLT(35)
  RandomNum(7,7)
  Global("flDisabled7","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled7","LOCALS",1)
    DisplayStringHead(Myself,@1335)
    ReallyForceSpellRES("fl#h30",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(34)
  DamageTakenLT(40)
  RandomNum(7,7)
  Global("flDisabled7","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled7","LOCALS",1)
    DisplayStringHead(Myself,@1335)
    ReallyForceSpellRES("fl#h35",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(39)
  RandomNum(7,7)
  Global("flDisabled7","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled7","LOCALS",1)
    DisplayStringHead(Myself,@1335)
    ReallyForceSpellRES("fl#h40",Myself)
  RESPONSE #90
    Continue()
END
