//Damage suffered by eyes is over and above the body's HP
IF
  IgnoreBlock(DeathTyrant)
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(29)
  RandomNum(11,1)
  Global("flDisabled1","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled1","LOCALS",1)
    DisplayStringHead(Myself,@1320)
    ReallyForceSpellRES("fl#h30",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(DeathTyrant)
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(24)
  RandomNum(11,1)
  Global("flDisabled1","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled1","LOCALS",1)
    DisplayStringHead(Myself,@1320)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(DeathTyrant)
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(19)
  RandomNum(11,1)
  Global("flDisabled1","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled1","LOCALS",1)
    DisplayStringHead(Myself,@1320)
    ReallyForceSpellRES("fl#h20",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(DeathTyrant)
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(14)
  RandomNum(11,1)
  Global("flDisabled1","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled1","LOCALS",1)
    DisplayStringHead(Myself,@1320)
    ReallyForceSpellRES("fl#h15",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(DeathTyrant)
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(9)
  RandomNum(11,1)
  Global("flDisabled1","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled1","LOCALS",1)
    DisplayStringHead(Myself,@1320)
    ReallyForceSpellRES("fl#h10",Myself)
  RESPONSE #85
    Continue()
END



IF
  IgnoreBlock(DeathTyrant)
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(29)
  RandomNum(11,2)
  Global("flDisabled2","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled2","LOCALS",1)
    DisplayStringHead(Myself,@1320)
    ReallyForceSpellRES("fl#h30",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(DeathTyrant)
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(24)
  RandomNum(11,2)
  Global("flDisabled2","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled2","LOCALS",1)
    DisplayStringHead(Myself,@1320)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(DeathTyrant)
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(19)
  RandomNum(11,2)
  Global("flDisabled2","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled2","LOCALS",1)
    DisplayStringHead(Myself,@1320)
    ReallyForceSpellRES("fl#h20",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(DeathTyrant)
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(14)
  RandomNum(11,2)
  Global("flDisabled2","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled2","LOCALS",1)
    DisplayStringHead(Myself,@1320)
    ReallyForceSpellRES("fl#h15",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(DeathTyrant)
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(9)
  RandomNum(11,2)
  Global("flDisabled2","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled2","LOCALS",1)
    DisplayStringHead(Myself,@1320)
    ReallyForceSpellRES("fl#h10",Myself)
  RESPONSE #85
    Continue()
END



IF
  RequireBlock(DeathTyrant)
  HitBy([ANYONE],0)
  DamageTakenGT(29)
  RandomNum(11,1)
  Global("flDisabled1","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled1","LOCALS",1)
    DisplayStringHead(Myself,@1321)
    ReallyForceSpellRES("fl#h30",Myself)
  RESPONSE #85
    Continue()
END

IF
  RequireBlock(DeathTyrant)
  HitBy([ANYONE],0)
  DamageTakenGT(24)
  RandomNum(11,1)
  Global("flDisabled1","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled1","LOCALS",1)
    DisplayStringHead(Myself,@1321)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #85
    Continue()
END

IF
  RequireBlock(DeathTyrant)
  HitBy([ANYONE],0)
  DamageTakenGT(19)
  RandomNum(11,1)
  Global("flDisabled1","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled1","LOCALS",1)
    DisplayStringHead(Myself,@1321)
    ReallyForceSpellRES("fl#h20",Myself)
  RESPONSE #85
    Continue()
END

IF
  RequireBlock(DeathTyrant)
  HitBy([ANYONE],0)
  DamageTakenGT(14)
  RandomNum(11,1)
  Global("flDisabled1","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled1","LOCALS",1)
    DisplayStringHead(Myself,@1321)
    ReallyForceSpellRES("fl#h15",Myself)
  RESPONSE #85
    Continue()
END

IF
  RequireBlock(DeathTyrant)
  HitBy([ANYONE],0)
  DamageTakenGT(9)
  RandomNum(11,1)
  Global("flDisabled1","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled1","LOCALS",1)
    DisplayStringHead(Myself,@1321)
    ReallyForceSpellRES("fl#h10",Myself)
  RESPONSE #85
    Continue()
END



IF
  RequireBlock(DeathTyrant)
  HitBy([ANYONE],0)
  DamageTakenGT(29)
  RandomNum(11,2)
  Global("flDisabled2","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled2","LOCALS",1)
    DisplayStringHead(Myself,@1321)
    ReallyForceSpellRES("fl#h30",Myself)
  RESPONSE #85
    Continue()
END

IF
  RequireBlock(DeathTyrant)
  HitBy([ANYONE],0)
  DamageTakenGT(24)
  RandomNum(11,2)
  Global("flDisabled2","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled2","LOCALS",1)
    DisplayStringHead(Myself,@1321)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #85
    Continue()
END

IF
  RequireBlock(DeathTyrant)
  HitBy([ANYONE],0)
  DamageTakenGT(19)
  RandomNum(11,2)
  Global("flDisabled2","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled2","LOCALS",1)
    DisplayStringHead(Myself,@1321)
    ReallyForceSpellRES("fl#h20",Myself)
  RESPONSE #85
    Continue()
END

IF
  RequireBlock(DeathTyrant)
  HitBy([ANYONE],0)
  DamageTakenGT(14)
  RandomNum(11,2)
  Global("flDisabled2","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled2","LOCALS",1)
    DisplayStringHead(Myself,@1321)
    ReallyForceSpellRES("fl#h15",Myself)
  RESPONSE #85
    Continue()
END

IF
  RequireBlock(DeathTyrant)
  HitBy([ANYONE],0)
  DamageTakenGT(9)
  RandomNum(11,2)
  Global("flDisabled2","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled2","LOCALS",1)
    DisplayStringHead(Myself,@1321)
    ReallyForceSpellRES("fl#h10",Myself)
  RESPONSE #85
    Continue()
END



IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(29)
  RandomNum(11,3)
  Global("flDisabled3","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled3","LOCALS",1)
    DisplayStringHead(Myself,@1322)
    ReallyForceSpellRES("fl#h30",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(24)
  RandomNum(11,3)
  Global("flDisabled3","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled3","LOCALS",1)
    DisplayStringHead(Myself,@1322)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(19)
  RandomNum(11,3)
  Global("flDisabled3","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled3","LOCALS",1)
    DisplayStringHead(Myself,@1322)
    ReallyForceSpellRES("fl#h20",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(14)
  RandomNum(11,3)
  Global("flDisabled3","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled3","LOCALS",1)
    DisplayStringHead(Myself,@1322)
    ReallyForceSpellRES("fl#h15",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(9)
  RandomNum(11,3)
  Global("flDisabled3","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled3","LOCALS",1)
    DisplayStringHead(Myself,@1322)
    ReallyForceSpellRES("fl#h10",Myself)
  RESPONSE #85
    Continue()
END



IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(29)
  RandomNum(11,4)
  Global("flDisabled4","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled4","LOCALS",1)
    DisplayStringHead(Myself,@1323)
    ReallyForceSpellRES("fl#h30",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(24)
  RandomNum(11,4)
  Global("flDisabled4","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled4","LOCALS",1)
    DisplayStringHead(Myself,@1323)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(19)
  RandomNum(11,4)
  Global("flDisabled4","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled4","LOCALS",1)
    DisplayStringHead(Myself,@1323)
    ReallyForceSpellRES("fl#h20",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(14)
  RandomNum(11,4)
  Global("flDisabled4","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled4","LOCALS",1)
    DisplayStringHead(Myself,@1323)
    ReallyForceSpellRES("fl#h15",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(9)
  RandomNum(11,4)
  Global("flDisabled4","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled4","LOCALS",1)
    DisplayStringHead(Myself,@1323)
    ReallyForceSpellRES("fl#h10",Myself)
  RESPONSE #85
    Continue()
END



IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(29)
  RandomNum(11,5)
  Global("flDisabled5","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled5","LOCALS",1)
    DisplayStringHead(Myself,@1324)
    ReallyForceSpellRES("fl#h30",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(24)
  RandomNum(11,5)
  Global("flDisabled5","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled5","LOCALS",1)
    DisplayStringHead(Myself,@1324)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(19)
  RandomNum(11,5)
  Global("flDisabled5","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled5","LOCALS",1)
    DisplayStringHead(Myself,@1324)
    ReallyForceSpellRES("fl#h20",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(14)
  RandomNum(11,5)
  Global("flDisabled5","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled5","LOCALS",1)
    DisplayStringHead(Myself,@1324)
    ReallyForceSpellRES("fl#h15",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(9)
  RandomNum(11,5)
  Global("flDisabled5","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled5","LOCALS",1)
    DisplayStringHead(Myself,@1324)
    ReallyForceSpellRES("fl#h10",Myself)
  RESPONSE #85
    Continue()
END



IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(29)
  RandomNum(11,6)
  Global("flDisabled6","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled6","LOCALS",1)
    DisplayStringHead(Myself,@1325)
    ReallyForceSpellRES("fl#h30",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(24)
  RandomNum(11,6)
  Global("flDisabled6","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled6","LOCALS",1)
    DisplayStringHead(Myself,@1325)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(19)
  RandomNum(11,6)
  Global("flDisabled6","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled6","LOCALS",1)
    DisplayStringHead(Myself,@1325)
    ReallyForceSpellRES("fl#h20",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(14)
  RandomNum(11,6)
  Global("flDisabled6","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled6","LOCALS",1)
    DisplayStringHead(Myself,@1325)
    ReallyForceSpellRES("fl#h15",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(9)
  RandomNum(11,6)
  Global("flDisabled6","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled6","LOCALS",1)
    DisplayStringHead(Myself,@1325)
    ReallyForceSpellRES("fl#h10",Myself)
  RESPONSE #85
    Continue()
END



IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(29)
  RandomNum(11,7)
  Global("flDisabled7","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled7","LOCALS",1)
    DisplayStringHead(Myself,@1326)
    ReallyForceSpellRES("fl#h30",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(24)
  RandomNum(11,7)
  Global("flDisabled7","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled7","LOCALS",1)
    DisplayStringHead(Myself,@1326)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(19)
  RandomNum(11,7)
  Global("flDisabled7","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled7","LOCALS",1)
    DisplayStringHead(Myself,@1326)
    ReallyForceSpellRES("fl#h20",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(14)
  RandomNum(11,7)
  Global("flDisabled7","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled7","LOCALS",1)
    DisplayStringHead(Myself,@1326)
    ReallyForceSpellRES("fl#h15",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(9)
  RandomNum(11,7)
  Global("flDisabled7","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled7","LOCALS",1)
    DisplayStringHead(Myself,@1326)
    ReallyForceSpellRES("fl#h10",Myself)
  RESPONSE #85
    Continue()
END



IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(29)
  RandomNum(11,8)
  Global("flDisabled8","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled8","LOCALS",1)
    DisplayStringHead(Myself,@1327)
    ReallyForceSpellRES("fl#h30",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(24)
  RandomNum(11,8)
  Global("flDisabled8","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled8","LOCALS",1)
    DisplayStringHead(Myself,@1327)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(19)
  RandomNum(11,8)
  Global("flDisabled8","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled8","LOCALS",1)
    DisplayStringHead(Myself,@1327)
    ReallyForceSpellRES("fl#h20",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(14)
  RandomNum(11,8)
  Global("flDisabled8","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled8","LOCALS",1)
    DisplayStringHead(Myself,@1327)
    ReallyForceSpellRES("fl#h15",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(9)
  RandomNum(11,8)
  Global("flDisabled8","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled8","LOCALS",1)
    DisplayStringHead(Myself,@1327)
    ReallyForceSpellRES("fl#h10",Myself)
  RESPONSE #85
    Continue()
END



IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(29)
  RandomNum(11,9)
  Global("flDisabled9","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled9","LOCALS",1)
    DisplayStringHead(Myself,@1328)
    ReallyForceSpellRES("fl#h30",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(24)
  RandomNum(11,9)
  Global("flDisabled9","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled9","LOCALS",1)
    DisplayStringHead(Myself,@1328)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(19)
  RandomNum(11,9)
  Global("flDisabled9","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled9","LOCALS",1)
    DisplayStringHead(Myself,@1328)
    ReallyForceSpellRES("fl#h20",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(14)
  RandomNum(11,9)
  Global("flDisabled9","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled9","LOCALS",1)
    DisplayStringHead(Myself,@1328)
    ReallyForceSpellRES("fl#h15",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(9)
  RandomNum(11,9)
  Global("flDisabled9","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled9","LOCALS",1)
    DisplayStringHead(Myself,@1328)
    ReallyForceSpellRES("fl#h10",Myself)
  RESPONSE #85
    Continue()
END



IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(29)
  RandomNum(11,10)
  Global("flDisabled10","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled10","LOCALS",1)
    DisplayStringHead(Myself,@1329)
    ReallyForceSpellRES("fl#h30",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(24)
  RandomNum(11,10)
  Global("flDisabled10","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled10","LOCALS",1)
    DisplayStringHead(Myself,@1329)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(19)
  RandomNum(11,10)
  Global("flDisabled10","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled10","LOCALS",1)
    DisplayStringHead(Myself,@1329)
    ReallyForceSpellRES("fl#h20",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(14)
  RandomNum(11,10)
  Global("flDisabled10","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled10","LOCALS",1)
    DisplayStringHead(Myself,@1329)
    ReallyForceSpellRES("fl#h15",Myself)
  RESPONSE #85
    Continue()
END

IF
  IgnoreBlock(HiveMother)
  HitBy([ANYONE],0)
  DamageTakenGT(9)
  RandomNum(11,10)
  Global("flDisabled10","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #15
    SetGlobal("flDisabled10","LOCALS",1)
    DisplayStringHead(Myself,@1329)
    ReallyForceSpellRES("fl#h10",Myself)
  RESPONSE #85
    Continue()
END



IF
  HitBy([ANYONE],0)
  DamageTakenGT(29)
  RandomNum(11,11)
  Global("flDisabled11","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled11","LOCALS",1)
    DisplayStringHead(Myself,@1330)
    ReallyForceSpellRES("fl#h30",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(24)
  RandomNum(11,11)
  Global("flDisabled11","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled11","LOCALS",1)
    DisplayStringHead(Myself,@1330)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(19)
  RandomNum(11,11)
  Global("flDisabled11","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled11","LOCALS",1)
    DisplayStringHead(Myself,@1330)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #90
    Continue()
END

IF
  HitBy([ANYONE],0)
  DamageTakenGT(14)
  RandomNum(11,11)
  Global("flDisabled11","LOCALS",0)
  !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
  RESPONSE #10
    SetGlobal("flDisabled11","LOCALS",1)
    DisplayStringHead(Myself,@1330)
    ReallyForceSpellRES("fl#h25",Myself)
  RESPONSE #90
    Continue()
END
