IF
  IsOverMe([ANYONE])
  Dead("Solaufein")
  !PartyHasItem("misc9v")
  Global("fl#fakeeggs","GLOBAL",0)
  Global("PhaereJob","GLOBAL",10)
  Global("DrowCityHostile","GLOBAL",0)
THEN
  RESPONSE #100
    StartCutSceneMode()
    CreateCreatureDoor("fl#udimp",[4144.2457],4)
    SetGlobal("fl#fakeeggs","GLOBAL",1)
    Wait(4)
    ActionOverride("fl#udimp",StartDialogueNoSet([PC]))
    EndCutSceneMode()
END
