INCLUDE FILE(fiends/include/ultroloth/call_lightning.ssl)

INCLUDE FILE(fiends/include/ultroloth/firestorm.ssl)

INCLUDE FILE(fiends/include/ultroloth/symbol.ssl)

INCLUDE FILE(fiends/include/ultroloth/gaze.ssl)

INCLUDE FILE(fiends/include/ultroloth/animate_dead.ssl)

INCLUDE FILE(fiends/include/ultroloth/cause_disease.ssl)

INCLUDE FILE(fiends/include/ultroloth/shout.ssl)

INCLUDE FILE(fiends/include/ultroloth/fear.ssl)

INCLUDE FILE(fiends/include/ultroloth/mass_suggestion.ssl)

INCLUDE FILE(fiends/include/ultroloth/colour_spray.ssl)

INCLUDE FILE(fiends/include/ultroloth/produce_flame.ssl)

INCLUDE FILE(fiends/include/ultroloth/charm_person.ssl)
